<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $list = [
            ["name" => ["en" => "Afghanistan", "ar" => "أفغانستان"], "dial_code" => "93", "code_alpha2" => "AF", "code_alpha3" => "AFG"],
            ["name" => ["en" => "Aland Islands", "ar" => "جزر آلاند"], "dial_code" => "358", "code_alpha2" => "AX", "code_alpha3" => "ALA"],
            ["name" => ["en" => "Albania", "ar" => "ألبانيا"], "dial_code" => "355", "code_alpha2" => "AL", "code_alpha3" => "ALB"],
            ["name" => ["en" => "Algeria", "ar" => "الجزائر"], "dial_code" => "213", "code_alpha2" => "DZ", "code_alpha3" => "DZA"],
            ["name" => ["en" => "AmericanSamoa", "ar" => "ساموا الأمريكية"], "dial_code" => "1684", "code_alpha2" => "AS", "code_alpha3" => "ASM"],
            ["name" => ["en" => "Andorra", "ar" => "أندورا"], "dial_code" => "376", "code_alpha2" => "AD", "code_alpha3" => "AND"],
            ["name" => ["en" => "Angola", "ar" => "أنغولا"], "dial_code" => "244", "code_alpha2" => "AO", "code_alpha3" => "AGO"],
            ["name" => ["en" => "Anguilla", "ar" => "أنغويلا"], "dial_code" => "1264", "code_alpha2" => "AI", "code_alpha3" => "AIA"],
            ["name" => ["en" => "Antarctica", "ar" => "القطب الجنوبي"], "dial_code" => "672", "code_alpha2" => "AQ", "code_alpha3" => "ATA"],
            ["name" => ["en" => "Antigua and Barbuda", "ar" => "أنتيغوا وبربودا"], "dial_code" => "1268", "code_alpha2" => "AG", "code_alpha3" => "ATG"],
            ["name" => ["en" => "Argentina", "ar" => "الأرجنتين"], "dial_code" => "54", "code_alpha2" => "AR", "code_alpha3" => "ARG"],
            ["name" => ["en" => "Armenia", "ar" => "أرمينيا"], "dial_code" => "374", "code_alpha2" => "AM", "code_alpha3" => "ARM"],
            ["name" => ["en" => "Aruba", "ar" => "أروبا"], "dial_code" => "297", "code_alpha2" => "AW", "code_alpha3" => "ABW"],
            ["name" => ["en" => "Australia", "ar" => "أستراليا"], "dial_code" => "61", "code_alpha2" => "AU", "code_alpha3" => "AUS"],
            ["name" => ["en" => "Austria", "ar" => "النمسا"], "dial_code" => "43", "code_alpha2" => "AT", "code_alpha3" => "AUT"],
            ["name" => ["en" => "Azerbaijan", "ar" => "أذربيجان"], "dial_code" => "994", "code_alpha2" => "AZ", "code_alpha3" => "AZE"],
            ["name" => ["en" => "Bahamas", "ar" => "الباهاما"], "dial_code" => "1242", "code_alpha2" => "BS", "code_alpha3" => "BHS"],
            ["name" => ["en" => "Bahrain", "ar" => "البحرين"], "dial_code" => "973", "code_alpha2" => "BH", "code_alpha3" => "BHR"],
            ["name" => ["en" => "Bangladesh", "ar" => "بنغلاديش"], "dial_code" => "880", "code_alpha2" => "BD", "code_alpha3" => "BGD"],
            ["name" => ["en" => "Barbados", "ar" => "بربادوس"], "dial_code" => "1246", "code_alpha2" => "BB", "code_alpha3" => "BRB"],
            ["name" => ["en" => "Belarus", "ar" => "بيلاروس"], "dial_code" => "375", "code_alpha2" => "BY", "code_alpha3" => "BLR"],
            ["name" => ["en" => "Belgium", "ar" => "بلجيكا"], "dial_code" => "32", "code_alpha2" => "BE", "code_alpha3" => "BEL"],
            ["name" => ["en" => "Belize", "ar" => "بليز"], "dial_code" => "501", "code_alpha2" => "BZ", "code_alpha3" => "BLZ"],
            ["name" => ["en" => "Benin", "ar" => "بنين"], "dial_code" => "229", "code_alpha2" => "BJ", "code_alpha3" => "BEN"],
            ["name" => ["en" => "Bermuda", "ar" => "برمودا"], "dial_code" => "1441", "code_alpha2" => "BM", "code_alpha3" => "BMU"],
            ["name" => ["en" => "Bhutan", "ar" => "بوتان"], "dial_code" => "975", "code_alpha2" => "BT", "code_alpha3" => "BTN"],
            ["name" => ["en" => "Bolivia", "ar" => "بوليفيا"], "dial_code" => "591", "code_alpha2" => "BO", "code_alpha3" => "BOL"],
            ["name" => ["en" => "Bosnia and Herzegovina", "ar" => "البوسنة والهرسك"], "dial_code" => "387", "code_alpha2" => "BA", "code_alpha3" => "BIH"],
            ["name" => ["en" => "Botswana", "ar" => "بوتسوانا"], "dial_code" => "267", "code_alpha2" => "BW", "code_alpha3" => "BWA"],
            ["name" => ["en" => "Brazil", "ar" => "البرازيل"], "dial_code" => "55", "code_alpha2" => "BR", "code_alpha3" => "BRA"],
            ["name" => ["en" => "British Indian Ocean Territory", "ar" => "إقليم المحيط الهندي البريطاني"], "dial_code" => "246", "code_alpha2" => "IO", "code_alpha3" => "IOT"],
            ["name" => ["en" => "Brunei Darussalam", "ar" => "بروناي دار السلام"], "dial_code" => "673", "code_alpha2" => "BN", "code_alpha3" => "BRN"],
            ["name" => ["en" => "Bulgaria", "ar" => "بلغاريا"], "dial_code" => "359", "code_alpha2" => "BG", "code_alpha3" => "BGR"],
            ["name" => ["en" => "Burkina Faso", "ar" => "بوركينا فاسو"], "dial_code" => "226", "code_alpha2" => "BF", "code_alpha3" => "BFA"],
            ["name" => ["en" => "Burundi", "ar" => "بوروندي"], "dial_code" => "257", "code_alpha2" => "BI", "code_alpha3" => "BDI"],
            ["name" => ["en" => "Cambodia", "ar" => "كمبوديا"], "dial_code" => "855", "code_alpha2" => "KH", "code_alpha3" => "KHM"],
            ["name" => ["en" => "Cameroon", "ar" => "الكاميرون"], "dial_code" => "237", "code_alpha2" => "CM", "code_alpha3" => "CMR"],
            ["name" => ["en" => "Canada", "ar" => "كندا"], "dial_code" => "1", "code_alpha2" => "CA", "code_alpha3" => "CAN"],
            ["name" => ["en" => "Cape Verde", "ar" => "الرأس الأخضر"], "dial_code" => "238", "code_alpha2" => "CV", "code_alpha3" => "CPV"],
            ["name" => ["en" => "Cayman Islands", "ar" => "جزر كايمان"], "dial_code" => " 345", "code_alpha2" => "KY", "code_alpha3" => "CYM"],
            ["name" => ["en" => "Central African Republic", "ar" => "جمهورية أفريقيا الوسطى"], "dial_code" => "236", "code_alpha2" => "CF", "code_alpha3" => "CAF"],
            ["name" => ["en" => "Chad", "ar" => "تشاد"], "dial_code" => "235", "code_alpha2" => "TD", "code_alpha3" => "TCD"],
            ["name" => ["en" => "Chile", "ar" => "شيلي"], "dial_code" => "56", "code_alpha2" => "CL", "code_alpha3" => "CHL"],
            ["name" => ["en" => "China", "ar" => "الصين"], "dial_code" => "86", "code_alpha2" => "CN", "code_alpha3" => "CHN"],
            ["name" => ["en" => "Christmas Island", "ar" => "جزيرة الكريسماس"], "dial_code" => "61", "code_alpha2" => "CX", "code_alpha3" => "CXR"],
            ["name" => ["en" => "Cocos (Keeling) Islands", "ar" => "جزر كوكوس (كيلينغ)"], "dial_code" => "61", "code_alpha2" => "CC", "code_alpha3" => "CCK"],
            ["name" => ["en" => "Colombia", "ar" => "كولومبيا"], "dial_code" => "57", "code_alpha2" => "CO", "code_alpha3" => "COL"],
            ["name" => ["en" => "Comoros", "ar" => "جزر القمر"], "dial_code" => "269", "code_alpha2" => "KM", "code_alpha3" => "COM"],
            ["name" => ["en" => "Congo", "ar" => "الكونغو"], "dial_code" => "242", "code_alpha2" => "CG", "code_alpha3" => "COG"],
            ["name" => ["en" => "Congo, The Democratic Republic of the Congo", "ar" => "جمهورية الكونغو الديمقراطية"], "dial_code" => "243", "code_alpha2" => "CD", "code_alpha3" => "COD"],
            ["name" => ["en" => "Cook Islands", "ar" => "جزر كوك"], "dial_code" => "682", "code_alpha2" => "CK", "code_alpha3" => "COK"],
            ["name" => ["en" => "Costa Rica", "ar" => "كوستاريكا"], "dial_code" => "506", "code_alpha2" => "CR", "code_alpha3" => "CRI"],
            ["name" => ["en" => "Cote d\'Ivoire", "ar" => "ساحل العاج"], "dial_code" => "225", "code_alpha2" => "CI", "code_alpha3" => "CIV"],
            ["name" => ["en" => "Croatia", "ar" => "كرواتيا"], "dial_code" => "385", "code_alpha2" => "HR", "code_alpha3" => "HRV"],
            ["name" => ["en" => "Cuba", "ar" => "كوبا"], "dial_code" => "53", "code_alpha2" => "CU", "code_alpha3" => "CUB"],
            ["name" => ["en" => "Cyprus", "ar" => "قبرص"], "dial_code" => "357", "code_alpha2" => "CY", "code_alpha3" => "CYP"],
            ["name" => ["en" => "Czech Republic", "ar" => "الجمهورية التشيكية"], "dial_code" => "420", "code_alpha2" => "CZ", "code_alpha3" => "CZE"],
            ["name" => ["en" => "Denmark", "ar" => "الدانمارك"], "dial_code" => "45", "code_alpha2" => "DK", "code_alpha3" => "DNK"],
            ["name" => ["en" => "Djibouti", "ar" => "جيبوتي"], "dial_code" => "253", "code_alpha2" => "DJ", "code_alpha3" => "DJI"],
            ["name" => ["en" => "Dominica", "ar" => "دومينيكا"], "dial_code" => "1767", "code_alpha2" => "DM", "code_alpha3" => "DMA"],
            ["name" => ["en" => "Dominican Republic", "ar" => "جمهورية الدومينيكان"], "dial_code" => "1849", "code_alpha2" => "DO", "code_alpha3" => "DOM"],
            ["name" => ["en" => "Ecuador", "ar" => "الإكوادور"], "dial_code" => "593", "code_alpha2" => "EC", "code_alpha3" => "ECU"],
            ["name" => ["en" => "Egypt", "ar" => "مصر"], "dial_code" => "20", "code_alpha2" => "EG", "code_alpha3" => "EGY"],
            ["name" => ["en" => "El Salvador", "ar" => "السلفادور"], "dial_code" => "503", "code_alpha2" => "SV", "code_alpha3" => "SLV"],
            ["name" => ["en" => "Equatorial Guinea", "ar" => "غينيا الاستوائية"], "dial_code" => "240", "code_alpha2" => "GQ", "code_alpha3" => "GNQ"],
            ["name" => ["en" => "Eritrea", "ar" => "إريتريا"], "dial_code" => "291", "code_alpha2" => "ER", "code_alpha3" => "ERI"],
            ["name" => ["en" => "Estonia", "ar" => "إستونيا"], "dial_code" => "372", "code_alpha2" => "EE", "code_alpha3" => "EST"],
            ["name" => ["en" => "Ethiopia", "ar" => "إثيوبيا"], "dial_code" => "251", "code_alpha2" => "ET", "code_alpha3" => "ETH"],
            ["name" => ["en" => "Falkland Islands (Malvinas)", "ar" => "جزر فوكلاند (مالفيناس)"], "dial_code" => "500", "code_alpha2" => "FK", "code_alpha3" => "FLK"],
            ["name" => ["en" => "Faroe Islands", "ar" => "جزر فارو"], "dial_code" => "298", "code_alpha2" => "FO", "code_alpha3" => "FRO"],
            ["name" => ["en" => "Fiji", "ar" => "فيجي"], "dial_code" => "679", "code_alpha2" => "FJ", "code_alpha3" => "FJI"],
            ["name" => ["en" => "Finland", "ar" => "فنلندا"], "dial_code" => "358", "code_alpha2" => "FI", "code_alpha3" => "FIN"],
            ["name" => ["en" => "France", "ar" => "فرنسا"], "dial_code" => "33", "code_alpha2" => "FR", "code_alpha3" => "FRA"],
            ["name" => ["en" => "French Guiana", "ar" => "غويانا الفرنسية"], "dial_code" => "594", "code_alpha2" => "GF", "code_alpha3" => "GUF"],
            ["name" => ["en" => "French Polynesia", "ar" => "بولينيزيا الفرنسية"], "dial_code" => "689", "code_alpha2" => "PF", "code_alpha3" => "PYF"],
            ["name" => ["en" => "Gabon", "ar" => "الغابون"], "dial_code" => "241", "code_alpha2" => "GA", "code_alpha3" => "GAB"],
            ["name" => ["en" => "Gambia", "ar" => "غامبيا"], "dial_code" => "220", "code_alpha2" => "GM", "code_alpha3" => "GMB"],
            ["name" => ["en" => "Georgia", "ar" => "جورجيا"], "dial_code" => "995", "code_alpha2" => "GE", "code_alpha3" => "GEO"],
            ["name" => ["en" => "Germany", "ar" => "ألمانيا"], "dial_code" => "49", "code_alpha2" => "DE", "code_alpha3" => "DEU"],
            ["name" => ["en" => "Ghana", "ar" => "غانا"], "dial_code" => "233", "code_alpha2" => "GH", "code_alpha3" => "GHA"],
            ["name" => ["en" => "Gibraltar", "ar" => "جبل طارق"], "dial_code" => "350", "code_alpha2" => "GI", "code_alpha3" => "GIB"],
            ["name" => ["en" => "Greece", "ar" => "اليونان"], "dial_code" => "30", "code_alpha2" => "GR", "code_alpha3" => "GRC"],
            ["name" => ["en" => "Greenland", "ar" => "جرينلاند"], "dial_code" => "299", "code_alpha2" => "GL", "code_alpha3" => "GRL"],
            ["name" => ["en" => "Grenada", "ar" => "غرينادا"], "dial_code" => "1473", "code_alpha2" => "GD", "code_alpha3" => "GRD"],
            ["name" => ["en" => "Guadeloupe", "ar" => "جوادلوب"], "dial_code" => "590", "code_alpha2" => "GP", "code_alpha3" => "GLP"],
            ["name" => ["en" => "Guam", "ar" => "غوام"], "dial_code" => "1671", "code_alpha2" => "GU", "code_alpha3" => "GUM"],
            ["name" => ["en" => "Guatemala", "ar" => "غواتيمالا"], "dial_code" => "502", "code_alpha2" => "GT", "code_alpha3" => "GTM"],
            ["name" => ["en" => "Guernsey", "ar" => "غيرنسي"], "dial_code" => "44", "code_alpha2" => "GG", "code_alpha3" => "GGY"],
            ["name" => ["en" => "Guinea", "ar" => "غينيا"], "dial_code" => "224", "code_alpha2" => "GN", "code_alpha3" => "GIN"],
            ["name" => ["en" => "Guinea-Bissau", "ar" => "غينيا بيساو"], "dial_code" => "245", "code_alpha2" => "GW", "code_alpha3" => "GNB"],
            ["name" => ["en" => "Guyana", "ar" => "غيانا"], "dial_code" => "595", "code_alpha2" => "GY", "code_alpha3" => "GUY"],
            ["name" => ["en" => "Haiti", "ar" => "هايتي"], "dial_code" => "509", "code_alpha2" => "HT", "code_alpha3" => "HTI"],
            ["name" => ["en" => "Holy See (Vatican City State)", "ar" => "الكرسي الرسولي (دولة الفاتيكان)"], "dial_code" => "379", "code_alpha2" => "VA", "code_alpha3" => "VAT"],
            ["name" => ["en" => "Honduras", "ar" => "هندوراس"], "dial_code" => "504", "code_alpha2" => "HN", "code_alpha3" => "HND"],
            ["name" => ["en" => "Hong Kong", "ar" => "هونغ كونغ"], "dial_code" => "852", "code_alpha2" => "HK", "code_alpha3" => "HKG"],
            ["name" => ["en" => "Hungary", "ar" => "هنغاريا"], "dial_code" => "36", "code_alpha2" => "HU", "code_alpha3" => "HUN"],
            ["name" => ["en" => "Iceland", "ar" => "أيسلندا"], "dial_code" => "354", "code_alpha2" => "IS", "code_alpha3" => "ISL"],
            ["name" => ["en" => "India", "ar" => "الهند"], "dial_code" => "91", "code_alpha2" => "IN", "code_alpha3" => "IND"],
            ["name" => ["en" => "Indonesia", "ar" => "إندونيسيا"], "dial_code" => "62", "code_alpha2" => "ID", "code_alpha3" => "IDN"],
            ["name" => ["en" => "Iran, Islamic Republic of Persian Gulf", "ar" => "جمهورية إيران الإسلامية"], "dial_code" => "98", "code_alpha2" => "IR", "code_alpha3" => "IRN"],
            ["name" => ["en" => "Iraq", "ar" => "العراق"], "dial_code" => "964", "code_alpha2" => "IQ", "code_alpha3" => "IRQ"],
            ["name" => ["en" => "Ireland", "ar" => "أيرلندا"], "dial_code" => "353", "code_alpha2" => "IE", "code_alpha3" => "IRL"],
            ["name" => ["en" => "Isle of Man", "ar" => "جزيرة مان"], "dial_code" => "44", "code_alpha2" => "IM", "code_alpha3" => "IMN"],
            ["name" => ["en" => "Italy", "ar" => "إيطاليا"], "dial_code" => "39", "code_alpha2" => "IT", "code_alpha3" => "ITA"],
            ["name" => ["en" => "Jamaica", "ar" => "جامايكا"], "dial_code" => "1876", "code_alpha2" => "JM", "code_alpha3" => "JAM"],
            ["name" => ["en" => "Japan", "ar" => "اليابان"], "dial_code" => "81", "code_alpha2" => "JP", "code_alpha3" => "JPN"],
            ["name" => ["en" => "Jersey", "ar" => "جيرسي"], "dial_code" => "44", "code_alpha2" => "JE", "code_alpha3" => "JEY"],
            ["name" => ["en" => "Jordan", "ar" => "الأردن"], "dial_code" => "962", "code_alpha2" => "JO", "code_alpha3" => "JOR"],
            ["name" => ["en" => "Kazakhstan", "ar" => "كازاخستان"], "dial_code" => "77", "code_alpha2" => "KZ", "code_alpha3" => "KAZ"],
            ["name" => ["en" => "Kenya", "ar" => "كينيا"], "dial_code" => "254", "code_alpha2" => "KE", "code_alpha3" => "KEN"],
            ["name" => ["en" => "Kiribati", "ar" => "كيريباتي"], "dial_code" => "686", "code_alpha2" => "KI", "code_alpha3" => "KIR"],
            ["name" => ["en" => "Korea, Democratic People\'s Republic of Korea", "ar" => "كوريا، جمهورية الشعب الديمقراطية"], "dial_code" => "850", "code_alpha2" => "KP", "code_alpha3" => "PRK"],
            ["name" => ["en" => "Korea, Republic of South Korea", "ar" => "كوريا، جمهورية"], "dial_code" => "82", "code_alpha2" => "KR", "code_alpha3" => "KOR"],
            ["name" => ["en" => "Kuwait", "ar" => "الكويت"], "dial_code" => "965", "code_alpha2" => "KW", "code_alpha3" => "KWT"],
            ["name" => ["en" => "Kyrgyzstan", "ar" => "قيرغيزستان"], "dial_code" => "996", "code_alpha2" => "KG", "code_alpha3" => "KGZ"],
            ["name" => ["en" => "Lao People'S Democratic Republic", "ar" => "جمهورية لاو الديمقراطية الشعبية"], "dial_code" => "856", "code_alpha2" => "LA", "code_alpha3" => "LAO"],
            ["name" => ["en" => "Latvia", "ar" => "لاتفيا"], "dial_code" => "371", "code_alpha2" => "LV", "code_alpha3" => "LVA"],
            ["name" => ["en" => "Lebanon", "ar" => "لبنان"], "dial_code" => "961", "code_alpha2" => "LB", "code_alpha3" => "LBN"],
            ["name" => ["en" => "Lesotho", "ar" => "ليسوتو"], "dial_code" => "266", "code_alpha2" => "LS", "code_alpha3" => "LSO"],
            ["name" => ["en" => "Liberia", "ar" => "ليبيريا"], "dial_code" => "231", "code_alpha2" => "LR", "code_alpha3" => "LBR"],
            ["name" => ["en" => "Libyan Arab Jamahiriya", "ar" => "الجماهيرية العربية الليبية"], "dial_code" => "218", "code_alpha2" => "LY", "code_alpha3" => "LBY"],
            ["name" => ["en" => "Liechtenstein", "ar" => "ليختنشتاين"], "dial_code" => "423", "code_alpha2" => "LI", "code_alpha3" => "LIE"],
            ["name" => ["en" => "Lithuania", "ar" => "ليتوانيا"], "dial_code" => "370", "code_alpha2" => "LT", "code_alpha3" => "LTU"],
            ["name" => ["en" => "Luxembourg", "ar" => "لوكسمبورغ"], "dial_code" => "352", "code_alpha2" => "LU", "code_alpha3" => "LUX"],
            ["name" => ["en" => "Macao", "ar" => "ماكاو"], "dial_code" => "853", "code_alpha2" => "MO", "code_alpha3" => "MAC"],
            ["name" => ["en" => "Macedonia", "ar" => "مقدونيا"], "dial_code" => "389", "code_alpha2" => "MK", "code_alpha3" => "MKD"],
            ["name" => ["en" => "Madagascar", "ar" => "مدغشقر"], "dial_code" => "261", "code_alpha2" => "MG", "code_alpha3" => "MDG"],
            ["name" => ["en" => "Malawi", "ar" => "ملاوي"], "dial_code" => "265", "code_alpha2" => "MW", "code_alpha3" => "MWI"],
            ["name" => ["en" => "Malaysia", "ar" => "ماليزيا"], "dial_code" => "60", "code_alpha2" => "MY", "code_alpha3" => "MYS"],
            ["name" => ["en" => "Maldives", "ar" => "المالديف"], "dial_code" => "960", "code_alpha2" => "MV", "code_alpha3" => "MDV"],
            ["name" => ["en" => "Mali", "ar" => "مالي"], "dial_code" => "223", "code_alpha2" => "ML", "code_alpha3" => "MLI"],
            ["name" => ["en" => "Malta", "ar" => "مالطا"], "dial_code" => "356", "code_alpha2" => "MT", "code_alpha3" => "MLT"],
            ["name" => ["en" => "Marshall Islands", "ar" => "جزر مارشال"], "dial_code" => "692", "code_alpha2" => "MH", "code_alpha3" => "MHL"],
            ["name" => ["en" => "Martinique", "ar" => "مارتينيك"], "dial_code" => "596", "code_alpha2" => "MQ", "code_alpha3" => "MTQ"],
            ["name" => ["en" => "Mauritania", "ar" => "موريتانيا"], "dial_code" => "222", "code_alpha2" => "MR", "code_alpha3" => "MRT"],
            ["name" => ["en" => "Mauritius", "ar" => "موريشيوس"], "dial_code" => "230", "code_alpha2" => "MU", "code_alpha3" => "MUS"],
            ["name" => ["en" => "Mayotte", "ar" => "مايوت"], "dial_code" => "262", "code_alpha2" => "YT", "code_alpha3" => "MYT"],
            ["name" => ["en" => "Mexico", "ar" => "المكسيك"], "dial_code" => "52", "code_alpha2" => "MX", "code_alpha3" => "MEX"],
            ["name" => ["en" => "Micronesia, Federated States of Micronesia", "ar" => "ميكرونيزيا، ولايات موحدة"], "dial_code" => "691", "code_alpha2" => "FM", "code_alpha3" => "FSM"],
            ["name" => ["en" => "Moldova, Republic of", "ar" => "مولدوفا، جمهورية"], "dial_code" => "373", "code_alpha2" => "MD", "code_alpha3" => "MDA"],
            ["name" => ["en" => "Monaco", "ar" => "موناكو"], "dial_code" => "377", "code_alpha2" => "MC", "code_alpha3" => "MCO"],
            ["name" => ["en" => "Mongolia", "ar" => "منغوليا"], "dial_code" => "976", "code_alpha2" => "MN", "code_alpha3" => "MNG"],
            ["name" => ["en" => "Montenegro", "ar" => "الجبل الأسود"], "dial_code" => "382", "code_alpha2" => "ME", "code_alpha3" => "MNE"],
            ["name" => ["en" => "Montserrat", "ar" => "مونتسيرات"], "dial_code" => "1664", "code_alpha2" => "MS", "code_alpha3" => "MSR"],
            ["name" => ["en" => "Morocco", "ar" => "المغرب"], "dial_code" => "212", "code_alpha2" => "MA", "code_alpha3" => "MAR"],
            ["name" => ["en" => "Mozambique", "ar" => "موزمبيق"], "dial_code" => "258", "code_alpha2" => "MZ", "code_alpha3" => "MOZ"],
            ["name" => ["en" => "Myanmar", "ar" => "ميانمار"], "dial_code" => "95", "code_alpha2" => "MM", "code_alpha3" => "MMR"],
            ["name" => ["en" => "Namibia", "ar" => "ناميبيا"], "dial_code" => "264", "code_alpha2" => "NA", "code_alpha3" => "NAM"],
            ["name" => ["en" => "Nauru", "ar" => "ناورو"], "dial_code" => "674", "code_alpha2" => "NR", "code_alpha3" => "NRU"],
            ["name" => ["en" => "Nepal", "ar" => "نيبال"], "dial_code" => "977", "code_alpha2" => "NP", "code_alpha3" => "NPL"],
            ["name" => ["en" => "Netherlands", "ar" => "هولندا"], "dial_code" => "31", "code_alpha2" => "NL", "code_alpha3" => "NLD"],
            ["name" => ["en" => "Netherlands Antilles", "ar" => "جزر الأنتيل الهولندية"], "dial_code" => "599", "code_alpha2" => "AN", "code_alpha3" => "ANT"],
            ["name" => ["en" => "New Caledonia", "ar" => "كاليدونيا الجديدة"], "dial_code" => "687", "code_alpha2" => "NC", "code_alpha3" => "NCL"],
            ["name" => ["en" => "New Zealand", "ar" => "نيوزيلندا"], "dial_code" => "64", "code_alpha2" => "NZ", "code_alpha3" => "NZL"],
            ["name" => ["en" => "Nicaragua", "ar" => "نيكاراغوا"], "dial_code" => "505", "code_alpha2" => "NI", "code_alpha3" => "NIC"],
            ["name" => ["en" => "Niger", "ar" => "النيجر"], "dial_code" => "227", "code_alpha2" => "NE", "code_alpha3" => "NER"],
            ["name" => ["en" => "Nigeria", "ar" => "نيجيريا"], "dial_code" => "234", "code_alpha2" => "NG", "code_alpha3" => "NGA"],
            ["name" => ["en" => "Niue", "ar" => "نيوي"], "dial_code" => "683", "code_alpha2" => "NU", "code_alpha3" => "NIU"],
            ["name" => ["en" => "Norfolk Island", "ar" => "جزيرة نورفولك"], "dial_code" => "672", "code_alpha2" => "NF", "code_alpha3" => "NFK"],
            ["name" => ["en" => "Northern Mariana Islands", "ar" => "جزر ماريانا الشمالية"], "dial_code" => "1670", "code_alpha2" => "MP", "code_alpha3" => "MNP"],
            ["name" => ["en" => "Norway", "ar" => "النرويج"], "dial_code" => "47", "code_alpha2" => "NO", "code_alpha3" => "NOR"],
            ["name" => ["en" => "Oman", "ar" => "عُمان"], "dial_code" => "968", "code_alpha2" => "OM", "code_alpha3" => "OMN"],
            ["name" => ["en" => "Pakistan", "ar" => "باكستان"], "dial_code" => "92", "code_alpha2" => "PK", "code_alpha3" => "PAK"],
            ["name" => ["en" => "Palau", "ar" => "بالاو"], "dial_code" => "680", "code_alpha2" => "PW", "code_alpha3" => "PLW"],
            ["name" => ["en" => "Palestine", "ar" => "فلسطين"], "dial_code" => "970", "code_alpha2" => "PS", "code_alpha3" => "PSE"],
            ["name" => ["en" => "Panama", "ar" => "بنما"], "dial_code" => "507", "code_alpha2" => "PA", "code_alpha3" => "PAN"],
            ["name" => ["en" => "Papua New Guinea", "ar" => "بابوا غينيا الجديد"], "dial_code" => "675", "code_alpha2" => "PG", "code_alpha3" => "PNG"],
            ["name" => ["en" => "Paraguay", "ar" => "باراغواي"], "dial_code" => "595", "code_alpha2" => "PY", "code_alpha3" => "PRY"],
            ["name" => ["en" => "Peru", "ar" => "بيرو"], "dial_code" => "51", "code_alpha2" => "PE", "code_alpha3" => "PER"],
            ["name" => ["en" => "Philippines", "ar" => "الفلبين"], "dial_code" => "63", "code_alpha2" => "PH", "code_alpha3" => "PHL"],
            ["name" => ["en" => "Pitcairn", "ar" => "بيتكيرن"], "dial_code" => "872", "code_alpha2" => "PN", "code_alpha3" => "PCN"],
            ["name" => ["en" => "Poland", "ar" => "بولندا"], "dial_code" => "48", "code_alpha2" => "PL", "code_alpha3" => "POL"],
            ["name" => ["en" => "Portugal", "ar" => "البرتغال"], "dial_code" => "351", "code_alpha2" => "PT", "code_alpha3" => "PRT"],
            ["name" => ["en" => "Puerto Rico", "ar" => "بورتوريكو"], "dial_code" => "1939", "code_alpha2" => "PR", "code_alpha3" => "PRI"],
            ["name" => ["en" => "Qatar", "ar" => "قطر"], "dial_code" => "974", "code_alpha2" => "QA", "code_alpha3" => "QAT"],
            ["name" => ["en" => "Reunion", "ar" => "لا ريونيون"], "dial_code" => "262", "code_alpha2" => "RE", "code_alpha3" => "REU"],
            ["name" => ["en" => "Romania", "ar" => "رومانيا"], "dial_code" => "40", "code_alpha2" => "RO", "code_alpha3" => "ROU"],
            ["name" => ["en" => "Russia Federation", "ar" => "الاتحاد الروسي"], "dial_code" => "7", "code_alpha2" => "RU", "code_alpha3" => "RUS"],
            ["name" => ["en" => "Rwanda", "ar" => "رواندا"], "dial_code" => "250", "code_alpha2" => "RW", "code_alpha3" => "RWA"],
            ["name" => ["en" => "Saint Barthelemy", "ar" => "سانت بارتيليمي"], "dial_code" => "590", "code_alpha2" => "BL", "code_alpha3" => "BLM"],
            ["name" => ["en" => "Saint Helena", "ar" => "سانت هيلينا"], "dial_code" => "290", "code_alpha2" => "SH", "code_alpha3" => "SHN"],
            ["name" => ["en" => "Saint Kitts and Nevis", "ar" => "سانت كيتس ونيفيس"], "dial_code" => "1869", "code_alpha2" => "KN", "code_alpha3" => "KNA"],
            ["name" => ["en" => "Saint Lucia", "ar" => "سانت لوسيا"], "dial_code" => "1758", "code_alpha2" => "LC", "code_alpha3" => "LCA"],
            ["name" => ["en" => "Saint Martin", "ar" => "سانت مارتن"], "dial_code" => "590", "code_alpha2" => "MF", "code_alpha3" => "MAF"],
            ["name" => ["en" => "Saint Pierre and Miquelon", "ar" => "سانت بيير وميكلون"], "dial_code" => "508", "code_alpha2" => "PM", "code_alpha3" => "SPM"],
            ["name" => ["en" => "Saint Vincent and the Grenadines", "ar" => "سانت فنسنت والغرينادين"], "dial_code" => "1784", "code_alpha2" => "VC", "code_alpha3" => "VCT"],
            ["name" => ["en" => "Samoa", "ar" => "ساموا"], "dial_code" => "685", "code_alpha2" => "WS", "code_alpha3" => "WSM"],
            ["name" => ["en" => "San Marino", "ar" => "سان مارينو"], "dial_code" => "378", "code_alpha2" => "SM", "code_alpha3" => "SMR"],
            ["name" => ["en" => "Sao Tome and Principe", "ar" => "ساو تومي وبرينسيبي"], "dial_code" => "239", "code_alpha2" => "ST", "code_alpha3" => "STP"],
            ["name" => ["en" => "Saudi Arabia", "ar" => "المملكة العربية السعودية"], "dial_code" => "966", "code_alpha2" => "SA", "code_alpha3" => "SAU"],
            ["name" => ["en" => "Senegal", "ar" => "السنغال"], "dial_code" => "221", "code_alpha2" => "SN", "code_alpha3" => "SEN"],
            ["name" => ["en" => "Serbia", "ar" => "صربيا"], "dial_code" => "381", "code_alpha2" => "RS", "code_alpha3" => "SRB"],
            ["name" => ["en" => "Seychelles", "ar" => "سيشيل"], "dial_code" => "248", "code_alpha2" => "SC", "code_alpha3" => "SYC"],
            ["name" => ["en" => "Sierra Leone", "ar" => "سيراليون"], "dial_code" => "232", "code_alpha2" => "SL", "code_alpha3" => "SLE"],
            ["name" => ["en" => "Singapore", "ar" => "سنغافورة"], "dial_code" => "65", "code_alpha2" => "SG", "code_alpha3" => "SGP"],
            ["name" => ["en" => "Slovakia", "ar" => "سلوفاكيا"], "dial_code" => "421", "code_alpha2" => "SK", "code_alpha3" => "SVK"],
            ["name" => ["en" => "Slovenia", "ar" => "سلوفينيا"], "dial_code" => "386", "code_alpha2" => "SI", "code_alpha3" => "SVN"],
            ["name" => ["en" => "Solomon Islands", "ar" => "جزر سليمان"], "dial_code" => "677", "code_alpha2" => "SB", "code_alpha3" => "SLB"],
            ["name" => ["en" => "Somalia", "ar" => "الصومال"], "dial_code" => "252", "code_alpha2" => "SO", "code_alpha3" => "SOM"],
            ["name" => ["en" => "South Africa", "ar" => "جنوب أفريقيا"], "dial_code" => "27", "code_alpha2" => "ZA", "code_alpha3" => "ZAF"],
            ["name" => ["en" => "South Sudan", "ar" => "جنوب السودان"], "dial_code" => "211", "code_alpha2" => "SS", "code_alpha3" => "SSD"],
            ["name" => ["en" => "South Georgia and the South Sandwich Islands", "ar" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية"], "dial_code" => "500", "code_alpha2" => "GS", "code_alpha3" => "SGS"],
            ["name" => ["en" => "Spain", "ar" => "إسبانيا"], "dial_code" => "34", "code_alpha2" => "ES", "code_alpha3" => "ESP"],
            ["name" => ["en" => "Sri Lanka", "ar" => "سريلانكا"], "dial_code" => "94", "code_alpha2" => "LK", "code_alpha3" => "LKA"],
            ["name" => ["en" => "Sudan", "ar" => "السودان"], "dial_code" => "249", "code_alpha2" => "SD", "code_alpha3" => "SDN"],
            ["name" => ["en" => "Suriname", "ar" => "سورينام"], "dial_code" => "597", "code_alpha2" => "SR", "code_alpha3" => "SUR"],
            ["name" => ["en" => "Svalbard and Jan Mayen", "ar" => "سفالبارد ويان ماين"], "dial_code" => "47", "code_alpha2" => "SJ", "code_alpha3" => "SJM"],
            ["name" => ["en" => "Swaziland", "ar" => "سوازيلاند"], "dial_code" => "268", "code_alpha2" => "SZ", "code_alpha3" => "SWZ"],
            ["name" => ["en" => "Sweden", "ar" => "السويد"], "dial_code" => "46", "code_alpha2" => "SE", "code_alpha3" => "SWE"],
            ["name" => ["en" => "Switzerland", "ar" => "سويسرا"], "dial_code" => "41", "code_alpha2" => "CH", "code_alpha3" => "CHE"],
            ["name" => ["en" => "Syrian Arab Republic", "ar" => "الجمهورية العربية السورية"], "dial_code" => "963", "code_alpha2" => "SY", "code_alpha3" => "SYR"],
            ["name" => ["en" => "Taiwan", "ar" => "تايوان"], "dial_code" => "886", "code_alpha2" => "TW", "code_alpha3" => "TWN"],
            ["name" => ["en" => "Tajikistan, United Republic of", "ar" => "تنزانيا، جمهورية متحدة"], "dial_code" => "992", "code_alpha2" => "TJ", "code_alpha3" => "TJK"],
            ["name" => ["en" => "Tanzania, United Republic of Tanzania", "ar" => "Tanzania, United Republic of Tanzania"], "dial_code" => "255", "code_alpha2" => "TZ", "code_alpha3" => "TZA"],
            ["name" => ["en" => "Thailand", "ar" => "تايلاند"], "dial_code" => "66", "code_alpha2" => "TH", "code_alpha3" => "THA"],
            ["name" => ["en" => "Timor-Leste", "ar" => "تيمور الشرقية"], "dial_code" => "670", "code_alpha2" => "TL", "code_alpha3" => "TLS"],
            ["name" => ["en" => "Togo", "ar" => "توغو"], "dial_code" => "228", "code_alpha2" => "TG", "code_alpha3" => "TGO"],
            ["name" => ["en" => "Tokelau", "ar" => "توكيلاو"], "dial_code" => "690", "code_alpha2" => "TK", "code_alpha3" => "TKL"],
            ["name" => ["en" => "Tonga", "ar" => "تونغا"], "dial_code" => "676", "code_alpha2" => "TO", "code_alpha3" => "TON"],
            ["name" => ["en" => "Trinidad and Tobago", "ar" => "ترينيداد وتوباغو"], "dial_code" => "1868", "code_alpha2" => "TT", "code_alpha3" => "TTO"],
            ["name" => ["en" => "Tunisia", "ar" => "تونس"], "dial_code" => "216", "code_alpha2" => "TN", "code_alpha3" => "TUN"],
            ["name" => ["en" => "Turkey", "ar" => "تركيا"], "dial_code" => "90", "code_alpha2" => "TR", "code_alpha3" => "TUR"],
            ["name" => ["en" => "Turkmenistan", "ar" => "تركمانستان"], "dial_code" => "993", "code_alpha2" => "TM", "code_alpha3" => "TKM"],
            ["name" => ["en" => "Turks and Caicos Islands", "ar" => "جزر تركس وكايكوس"], "dial_code" => "1649", "code_alpha2" => "TC", "code_alpha3" => "TCA"],
            ["name" => ["en" => "Tuvalu", "ar" => "توفالو"], "dial_code" => "688", "code_alpha2" => "TV", "code_alpha3" => "TUV"],
            ["name" => ["en" => "Uganda", "ar" => "أوغندا"], "dial_code" => "256", "code_alpha2" => "UG", "code_alpha3" => "UGA"],
            ["name" => ["en" => "Ukraine", "ar" => "أوكرانيا"], "dial_code" => "380", "code_alpha2" => "UA", "code_alpha3" => "UKR"],
            ["name" => ["en" => "United Arab Emirates", "ar" => "الإمارات العربية المتحدة"], "dial_code" => "971", "code_alpha2" => "AE", "code_alpha3" => "ARE"],
            ["name" => ["en" => "United Kingdom", "ar" => "المملكة المتحدة"], "dial_code" => "44", "code_alpha2" => "GB", "code_alpha3" => "GBR"],
            ["name" => ["en" => "United States", "ar" => "الولايات المتحدة"], "dial_code" => "1", "code_alpha2" => "US", "code_alpha3" => "USA"],
            ["name" => ["en" => "Uruguay", "ar" => "أوروغواي"], "dial_code" => "598", "code_alpha2" => "UY", "code_alpha3" => "URY"],
            ["name" => ["en" => "Uzbekistan", "ar" => "أوزبكستان"], "dial_code" => "998", "code_alpha2" => "UZ", "code_alpha3" => "UZB"],
            ["name" => ["en" => "Vanuatu", "ar" => "فانواتو"], "dial_code" => "678", "code_alpha2" => "VU", "code_alpha3" => "VUT"],
            ["name" => ["en" => "Venezuela", "ar" => "فنزويلا"], "dial_code" => "58", "code_alpha2" => "VE", "code_alpha3" => "VEN"],
            ["name" => ["en" => "Vietnam", "ar" => "فيتنام"], "dial_code" => "84", "code_alpha2" => "VN", "code_alpha3" => "VNM"],
            ["name" => ["en" => "Virgin Islands, British", "ar" => "جزر العذراء البريطانية"], "dial_code" => "1284", "code_alpha2" => "VG", "code_alpha3" => "VGB"],
            ["name" => ["en" => "Virgin Islands, U.S.", "ar" => "جزر العذراء الأمريكية"], "dial_code" => "1340", "code_alpha2" => "VI", "code_alpha3" => "VIR"],
            ["name" => ["en" => "Wallis and Futuna", "ar" => "واليس وفوتونا"], "dial_code" => "681", "code_alpha2" => "WF", "code_alpha3" => "WLF"],
            ["name" => ["en" => "Yemen", "ar" => "اليمن"], "dial_code" => "967", "code_alpha2" => "YE", "code_alpha3" => "YEM"],
            ["name" => ["en" => "Zambia", "ar" => "زامبيا"], "dial_code" => "260", "code_alpha2" => "ZM", "code_alpha3" => "ZMB"],
            ["name" => ["en" => "Zimbabwe", "ar" => "زيمبابوي"], "dial_code" => "263", "code_alpha2" => "ZW", "code_alpha3" => "Zimbabwe"],
        ];

        foreach ($list as $country)
        {
            Country::updateOrCreate(['code_alpha2' => $country['code_alpha2']], $country);
        }
    }
}
