<?php

namespace App\Filament\Tenant\Resources\ProductResource\Pages;

use App\Filament\Tenant\Resources\ProductResource;
use App\Models\ItemPrice;
use App\Services\PricingService;
use App\Services\StockService;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class EditProduct extends EditRecord
{
    protected static string $resource = ProductResource::class;

    protected function getHeaderActions(): array
    {
        return [
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['enable_variations'] = $this->record->variants->isNotEmpty();
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    protected function beforeValidate()
    {
        foreach ($this->data['variants'] ?? [] as $key => $variant) {
            if (isset($variant['should_remove']) and $variant['should_remove'])
                unset($this->data['variants'][$key]);
        }
    }

    protected function beforeSave(): void
    {
        $this->handlePricing($this->record, $this->data);
//        $this->redirect($this->getResource()::getUrl('edit', ['record' => $this->record->id]));
    }


    protected function handlePricing($record, $data): void
    {
        $record->refresh();

        //basic pricing
        if($record->variants->isEmpty()){
            PricingService::instance()->addPrice($record, null, $data['price'], $this->data['discount_price']);
        }

        foreach ($record->variants as $productVariant) {
            $itemInData = collect($data['variants'])->firstWhere('sku', $productVariant->sku);
            if($itemInData)
            {
                $itemPrice = PricingService::instance()->addPrice($productVariant, null, $itemInData['price'] ?? null, $itemInData['discount_price'] ?? null);
            }
        }

        foreach ($record->extras as $productExtra) {
            $itemInData = collect($data['extras_table'])->firstWhere('item_extra_id', $productExtra->item_extra_id);

            if($itemInData)
            {
                $itemPrice = PricingService::instance()->addPrice($productExtra, null, $itemInData['price'] ?? null, $itemInData['discount_price'] ?? null);
            }
        }
    }
}
