<?php

    namespace App\Filament\Tenant\Resources;

    use App\Filament\Tenant\Resources\Acc1Resource\Pages;
    use App\Filament\Tenant\Resources\Acc1Resource\RelationManagers;
    use App\Models\Acc1;
    use Filament\Forms\Components\Section;
    use Filament\Forms\Components\TextInput;
    use Filament\Forms\Form;
    use Filament\Resources\Resource;
    use Filament\Tables;
    use Illuminate\Database\Eloquent\Builder;

    class Acc1Resource extends Resource
    {
        protected static ?string $model = Acc1::class;

        protected static ?string $navigationIcon = 'heroicon-o-user-group';

        protected static ?string $recordTitleAttribute = "name";

        protected static ?string $slug = "finance/accounts";

        protected static ?int $navigationSort = 4;


        public static function getNavigationGroup(): ?string
        {
            return __('fields.finance');
        }

        public static function getLabel(): ?string
        {
            return __('fields.account');
        }

        public static function getPluralLabel(): ?string
        {
            return __('fields.level_1');
        }

        public static function shouldRegisterNavigation(): bool
        {
            return false;
        }

        public static function getNavigationBadge(): ?string
        {
            return static::getModel()::count();
        }

        public static function form(Form $form): Form
        {
            return $form
                ->schema([
                    Section::make([

                    ])
                ]);
        }

        public static function table(Tables\Table $table): Tables\Table
        {
            return $table
                ->columns([
                    Tables\Columns\TextColumn::make('name')
                        ->label(__('fields.name'))
                        ->searchable(),
                    Tables\Columns\TextColumn::make('code')
                        ->label(__('fields.code'))
                        ->searchable(),
                ])
                ->filters([
                ])
                ->actions([
                ]);
        }

        public static function getPages(): array
        {
            return [
                'index' => Pages\ManageAcc1s::route('/'),
            ];
        }

        public static function getEloquentQuery(): Builder
        {
            return parent::getEloquentQuery()->latest(); // TODO: Change the autogenerated stub
        }
    }
