<?php

    namespace App\Filament\Tenant\Resources;

    use App\Filament\Tenant\Resources\Acc2Resource\Pages;
    use App\Filament\Tenant\Resources\Acc2Resource\RelationManagers;
    use App\Models\Acc2;
    use Filament\Forms\Components\View;
    use Filament\Forms\Form;
    use Filament\Resources\Resource;
    use Filament\Tables;
    use Illuminate\Database\Eloquent\Builder;

    class Acc2Resource extends Resource
    {
        protected static ?string $model = Acc2::class;

        protected static ?string $navigationIcon = 'heroicon-o-user-group';

        protected static ?string $recordTitleAttribute = "name";

        protected static ?string $slug = "finance/tree-accounts/level-two";

        protected static ?int $navigationSort = 5;

        public static function getNavigationGroup(): ?string
        {
            return __('fields.finance');
        }

        public static function getLabel(): ?string
        {
            return __('fields.account');
        }

        public static function getPluralLabel(): ?string
        {
            return __('fields.level_2');
        }

        public static function shouldRegisterNavigation(): bool
        {
            return false;
        }

        public static function getNavigationBadge(): ?string
        {
            return static::getModel()::count();
        }

        public static function form(Form $form): Form
        {
            return $form
                ->schema([
                    View::make('components.loading'),

                ]);
        }

        public static function table(Tables\Table $table): Tables\Table
        {
            return $table
                ->columns([
                    Tables\Columns\TextColumn::make('name')
                        ->label(__('fields.name'))
                        ->searchable(),
                    Tables\Columns\TextColumn::make('code')
                        ->label(__('fields.code'))
                        ->searchable(),
                    Tables\Columns\TextColumn::make('acc1_code')
                        ->searchable()
                        ->getStateUsing(function ($record) {
                            return $record->acc1->name;
                        }),
                ])
                ->filters([
                    //
                ])
                ->actions([
                ]);
        }

        public static function getEloquentQuery(): Builder
        {
            return parent::getEloquentQuery()->with(['acc1'])->latest(); // TODO: Change the autogenerated stub
        }

        public static function getPages(): array
        {
            return [
                'index' => \App\Filament\Tenant\Resources\Acc2Resource\Pages\ManageAcc2s::route('/'),
            ];
        }
    }
