<?php

namespace App\Filament\Tenant\Resources;

use App\Filament\Tenant\Resources\Acc3Resource\Pages;
use App\Filament\Tenant\Resources\Acc3Resource\RelationManagers;
use App\Models\Acc3;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;

class Acc3Resource extends Resource
{
    protected static ?string $model = Acc3::class;

    protected static ?string $navigationIcon = 'heroicon-o-user-group';

    protected static ?string $recordTitleAttribute = "name";

    protected static ?string $slug = "finance/tree-accounts/level-three";

    protected static ?int $navigationSort = 6;


    public static function getNavigationGroup(): ?string
    {
        return __('fields.finance');
    }

    public static function getLabel(): ?string
    {
        return __('fields.account');
    }

    public static function getPluralLabel(): ?string
    {
        return __('fields.level_3');
    }

    public static function shouldRegisterNavigation(): bool
    {
        return false;
    }

    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count();
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }

    public static function table(Tables\Table $table): Tables\Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('fields.name'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('code')
                    ->label(__('fields.code'))
                    ->searchable(),
                Tables\Columns\TextColumn::make('acc2_code')
                    ->searchable()
                    ->description(function ($record){
                        return $record->acc2->code;
                    })
                    ->getStateUsing(function ($record) {
                        return $record->acc2->name;
                    }),
            ])
            ->filters([
                //
            ])
            ->actions([

            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->with(['acc2'])->latest(); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Tenant\Resources\Acc3Resource\Pages\ManageAcc3s::route('/'),
        ];
    }
}
