<?php

namespace App\Filament\Tenant\Resources;

use App\Filament\Tenant\Resources\CustomerResource\Pages;
use App\Filament\Tenant\Resources\CustomerResource\RelationManagers;
use App\Models\Customer;
use App\Rules\InternationalPhoneRule;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class CustomerResource extends Resource
{
    protected static ?string $model = Customer::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    protected static ?string $slug = "customers";

    protected static ?int $navigationSort = 2;


    public static function getLabel(): ?string
    {
        return __('fields.client');
    }


    public static function getPluralLabel(): ?string
    {
        return __('fields.clients');
    }

    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count();
    }

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make()
                    ->schema(self::getSchema())->columns(4)
            ]);
    }

    public static function getSchema(): array
    {
        return [

            hidden_tenant_id_field(),

            Forms\Components\TextInput::make('name')
                ->label(__('fields.name'))
                ->required()
                ->autofocus(),

            Forms\Components\TextInput::make('phone')
                ->label(__('fields.phone'))
                ->tel()
                ->rules([
                    new InternationalPhoneRule(false)
                ])
                ->required(),

            Forms\Components\TextInput::make('delivery_address')
                ->label(__('fields.delivery_address'))
                ->type('address')
                ->required(),

            Forms\Components\TextInput::make('email')
                ->label(__('fields.email'))
                ->email(),

        ];
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([

                Tables\Columns\TextColumn::make('no')->label(__('fields.reference_code'))->toggleable()->toggledHiddenByDefault()->searchable(),
                Tables\Columns\TextColumn::make('name')->label(__('fields.name'))->searchable(),
                Tables\Columns\TextColumn::make('phone')->label(__('fields.phone'))->searchable(),
                Tables\Columns\TextColumn::make('delivery_address')->label(__('fields.delivery_address'))->searchable(),
                Tables\Columns\TextColumn::make('email')->label(__('fields.email'))->searchable(),
                Tables\Columns\TextColumn::make('orders_count')->label(__('fields.orders'))->counts('orders'),

                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('fields.join_date'))
                    ->dateTime('M j, Y h:i')
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                ]),
            ]);
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->with(['orders'])->latest(); // TODO: Change the autogenerated stub
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListCustomers::route('/'),
            'create' => Pages\CreateCustomer::route('/create'),
            'edit' => Pages\EditCustomer::route('/{record}/edit'),
        ];
    }

}
