<?php

namespace App\Filament\Tenant\Resources;

use App\Filament\Tenant\Resources\SupplierResource\Pages;
use App\Models\Supplier;
use Filament\Forms;
use Filament\Resources\Resource;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;

class SupplierResource extends Resource
{
    protected static ?string $model = Supplier::class;

    protected static ?string $navigationIcon = 'heroicon-o-user-group';

    protected static ?string $slug = "purchases/suppliers";

    protected static ?int $navigationSort = 4;

    protected static bool $shouldRegisterNavigation = false;

    public static function getNavigationGroup(): ?string
    {
        return __('fields.products');
    }

    public static function getLabel(): ?string
    {
        return __('fields.supplier');
    }

    public static function getPluralLabel(): ?string
    {
        return __('fields.suppliers');
    }

    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count();
    }

    public static function getSchema(): array
    {
        return [
            Forms\Components\Section::make([

                Forms\Components\TextInput::make('name')
                    ->label(__('fields.name'))
                    ->autofocus()
                    ->required(),

                Forms\Components\TextInput::make('phone')
                    ->label(__('fields.phone'))
                    ->required(),

                Forms\Components\TextInput::make('company')
                    ->label(__('fields.company')),

                Forms\Components\TextInput::make('address')
                    ->label(__('fields.address')),


                Forms\Components\TextInput::make('email')
                    ->label(__('fields.email')),

            ])->columns(5),

            Forms\Components\Section::make([
                Forms\Components\RichEditor::make('notes')->label(__('fields.notes')),
            ])
        ];
    }

    public static function form(Forms\Form $form): Forms\Form
    {
        return $form
            ->schema(self::getSchema());
    }

    public static function table(Tables\Table $table): Tables\Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')->label(__('fields.name'))->searchable(),
                Tables\Columns\TextColumn::make('phone')->label(__('fields.phone'))->searchable(),
                Tables\Columns\TextColumn::make('address')->label(__('fields.address'))->searchable(),
                Tables\Columns\TextColumn::make('company')->label(__('fields.company'))->searchable(),
                Tables\Columns\TextColumn::make('email')->label(__('fields.email'))->searchable(),

                Tables\Columns\TextColumn::make('updated_at')
                    ->label(__('fields.updated_at'))
                    ->dateTime('M j, Y')
                    ->sortable(),

                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('fields.created_at'))
                    ->dateTime('M j, Y')
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
            ]);
    }

    public static function getRelations(): array
    {
        return [
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->latest(); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListSuppliers::route('/'),
            'create' => Pages\CreateSupplier::route('/create'),
            'edit' => Pages\EditSupplier::route('/{record}/edit'),
        ];
    }

}
