<?php

namespace App\Filament\Tenant\Resources;

use App\Filament\Tenant\Resources\UnitResource\Pages;
use App\Models\Unit;
use App\Rules\UniqueTenantItemRule;
use Filament\Forms;
use Filament\Notifications\Notification;
use Filament\Resources\Resource;
use Filament\Tables;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class UnitResource extends Resource
{
    protected static ?string $model = Unit::class;

    protected static ?string $navigationIcon = 'heroicon-o-scale';

    protected static ?string $slug = "warehouses/units";

    protected static ?int $navigationSort = 5;


    public static function shouldRegisterNavigation(): bool
    {
        return false;
    }

    public static function getNavigationGroup(): ?string
    {
        return __('fields.warehouses');
    }

    public static function getLabel(): ?string
    {
        return __('fields.unit');
    }

    public static function getPluralLabel(): ?string
    {
        return __('fields.units');
    }

    public static function getNavigationBadge(): ?string
    {
        return static::getModel()::count();
    }

    public static function form(Forms\Form $form): Forms\Form
    {
        return $form
            ->schema([
                Forms\Components\Section::make()
                    ->schema([
                        Forms\Components\TextInput::make('name')
                            ->label(__('fields.name'))
                            ->autofocus()
                            ->rules([new UniqueTenantItemRule(Unit::class, 'name', $form->getRecord()?->id)])
                            ->required(),
                    ])
            ]);
    }


    public static function table(Tables\Table $table): Tables\Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->label(__('fields.name')),

                Tables\Columns\TextColumn::make('created_at')
                    ->label(__('fields.created_at'))
                    ->sortable(),
            ])
            ->bulkActions([])
            ->actions([
                Tables\Actions\ActionGroup::make([
                    Tables\Actions\EditAction::make('edit'),
                    Tables\Actions\DeleteAction::make('delete')
                        ->action(function (Unit $record) {
                            try {
                                $record->delete();
                                Notification::make()
                                    ->title(__('fields.record_added_alert'))
                                    ->success()
                                    ->send();

                            } catch (\Exception $exception) {
                                Notification::make()
                                    ->title($exception->getMessage())
                                    ->danger()
                                    ->send();
                            }

                        })
                        ->requiresConfirmation()
                        ->color('danger'),
                ])
            ])
            ->filters([
                //
            ])->deferLoading();
    }

    public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->with([])->latest(); // TODO: Change the autogenerated stub
    }

    public static function getPages(): array
    {
        return [
            'index' => \App\Filament\Tenant\Resources\UnitResource\Pages\ManageUnits::route('/'),
        ];
    }

    public static function canViewAny(): bool
    {
        return parent::canViewAny(); // TODO: Change the autogenerated stub
    }
}
