<?php

namespace App\Filament\Tenant\Resources\ExpenseResource\Pages;

use App\Filament\Tenant\Resources\ExpenseResource;
use App\Models\ExpenseType;
use App\Services\AccountingService;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;

class CreateExpense extends CreateRecord
{
    protected static string $resource = ExpenseResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function getCreateFormAction(): Action
    {
        return Action::make('create')
            ->label(__('filament-panels::resources/pages/create-record.form.actions.create.label'))
            ->requiresConfirmation()
            ->keyBindings(['mod+s'])
            ->mountUsing(fn() => $this->form->validate())
            ->action(fn(Action $action) => $this->create());
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        unset($data['amount_includes_tax']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function afterCreate()
    {
        $op = make_taxes_op();
        $accService = new AccountingService();
        $accService
            ->setUp(
                $op->id,
                now(),
                main_currency_iso_code(),
                generate_double_entry_transaction_id(),
                $this->record->amount,
                null,
                $this->record->description,
                $this->record->description,
                null,
                meta: ['type' => 'expense', 'id' => $this->record->id],
            )->make($this->record->credit_acc4_code, '122300001')
            ->finish();

        if ($this->record->tax > 0) {
            $op = make_taxes_op();
            $accService = new AccountingService();
            $accService
                ->setUp(
                    $op->id,
                    now(),
                    main_currency_iso_code(),
                    generate_double_entry_transaction_id(),
                    $this->record->tax,
                    null,
                    'Vat',
                    'Vat',
                    null,
                    meta: ['type' => 'expense', 'id' => $this->record->id],
                )->make('120100001', '122800001')
                ->finish();
        }

    }
}
