<?php

namespace App\Filament\Tenant\Resources\ExpenseResource\Pages;

use App\Filament\Tenant\Resources\ExpenseResource;
use Filament\Resources\Pages\EditRecord;

class EditExpense extends EditRecord
{
    protected static string $resource = ExpenseResource::class;

    protected function getHeaderActions(): array
    {
        return [
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        if($data['tax'] > 0){
            $data['amount_includes_tax'] = true;
            $data['tax'] = number_format($data['tax'], currency_decimals(), '.', '');
            $data['amount_without_tax'] = number_format($data['amount'], currency_decimals(), '.', '');
            $data['amount'] = number_format($data['amount'] + $data['tax'], currency_decimals(), '.', '');
        }
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function afterSave()
    {
    }
}
