<?php

namespace App\Filament\Tenant\Resources\OrderResource\Pages;

use App\Filament\Tenant\Resources\OrderResource;
use App\Models\AdditionalCost;
use App\Models\AdditionalCostType;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\PriceOffer;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Services\PricingService;
use App\Services\StockService;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreateOrder extends CreateRecord
{
    protected static string $resource = OrderResource::class;


    protected function mutateFormDataBeforeCreate(array $data): array
    {
        unset($data['details']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    public function create(bool $another = false): void
    {
        $this->authorizeAccess();

        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        try {

            DB::beginTransaction();

            $data = $this->mutateFormDataBeforeCreate($data);

            $this->callHook('beforeCreate');

            $this->record = $this->handleRecordCreation($data);

            $this->form->model($this->getRecord())->saveRelationships();

            $this->saveItems($this->record->id, $this->data);

            $this->createInvoice($this->record);

            DB::commit();

            $this->callHook('afterCreate');

        } catch (Halt $exception) {
            DB::rollBack();
            return;
        } catch (ValidationException $exception) {
            DB::rollBack();
            return;
        } catch (\Throwable $exception) {
            DB::rollBack();
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            $this->halt();
        }

        $this->getCreatedNotification()?->send();

        if ($another) {
            // Ensure that the form record is anonymized so that relationships aren't loaded.
            $this->form->model($this->getRecord()::class);
            $this->record = null;

            $this->fillForm();

            return;
        }

        $redirectUrl = $this->getRedirectUrl();

        if (FilamentView::hasSpaMode()) {
            $this->redirect($redirectUrl, navigate: is_app_url($redirectUrl));
        } else {
            $this->redirect($redirectUrl);
        }

    }

    protected function createInvoice(Order $order): Invoice
    {
        $order->refresh();

        $tenant_id = filament()->getTenant()->id;

        $invoice = Invoice::create([
            'no' => generate_invoice_no(),
            'tenant_id' => $tenant_id,
            'type' => 'sales',
            'status' => 'sale_order',
            'for' => 'customer',
            'customer_id' => $order->customer_id,
            'user_id' => auth()->id(),
            'date' => now(),
            'notes' => 'sales',
        ]);

        $order->update(['invoice_id' => $invoice->id]);

        foreach ($order->details as $detail) {

            $product_id = null;
            $product_variant_id = null;

            if ($detail->item instanceof Product) {
                $product_id = $detail->item->id;
                $tax_profile_id = $detail->item->tax_profile_id;
            }

            if ($detail->item instanceof ProductVariant) {
                $product_id = $detail->item->product_id;
                $product_variant_id = $detail->item->id;
                $tax_profile_id = $detail->item->product->tax_profile_id;
            }

            $invoice->items()
                ->insert([
                    [
                        'tenant_id' => $tenant_id,
                        'invoice_id' => $invoice->id,
                        'product_id' => $product_id,
                        'product_variant_id' => $product_variant_id,
                        'order_details_id' => $detail->id,
                        'tax_profile_id' => $tax_profile_id,
                        'discount' => 0,
                        'qty' => $detail->qty,
                        'price' => $detail->unit_price,
                        'created_at' => now(),
                    ],
                ]);
        }

        $costTypeDelivery = AdditionalCostType::firstOrCreate([
            'name' => "توصيل/شحن"
        ], [
            'name' => "توصيل/شحن",
            'tenant_id' => filament()->getTenant()->id,
        ]);

        $statement_en = "Delivery fees, order no #$order->no";
        $statement_ar = "رسوم توصيل الطلب:#$order->no";

        AdditionalCost::create([
            'tenant_id' => filament()->getTenant()->id,
            'item_id' => $invoice->id,
            'item_type' => Invoice::class,
            'additional_cost_type_id' => $costTypeDelivery->id,
            'statement' => $statement_ar . " - " . $statement_en,
            'cost' => $order->delivery,
            'meta' => ['type' => 'delivery_fees', 'client' => $order->customer->name, 'client_id' => $order->customer_id]
        ]);

        return $invoice;
    }


    protected function saveItems($order_id, $data)
    {
        foreach ($data['details'] as $index => $detail) {
            $taxProfile = null;

            $item = app()->make($detail['item_type'])->where('id', $detail['item_id'])->first();

            if ($item instanceof Product) {
                $taxProfile = $item->taxProfile;
            }

            if ($item instanceof ProductVariant) {
                $taxProfile = $item->product->taxProfile;
            }

            if ($taxProfile)
                $taxProfile->load('taxes');

            $od = OrderDetail::create([
                'tenant_id' => $detail['tenant_id'],
                'order_id' => $order_id,
                'user_id' => auth()->id(),
                'item_id' => $detail['item_id'],
                'item_type' => $detail['item_type'],
                'unit_price' => $detail['unit_price'],
                'discount' => 0,
                'tax' => $detail['tax'],
                'qty' => $detail['qty'],
                'taken_qty' => 0,
                'cancelled' => 0,
                'tax_profile_data' => $taxProfile ? $taxProfile->toArray() : null,
            ]);

            foreach ($detail['product_extras_ids'] ?? [] as $product_extra_id) {

                $productExtra = ProductExtra::with(['lastPrice', 'extra'])->findOrFail($product_extra_id);

                $od->orderDetailsExtras()->create([
                    'tenant_id' => $detail['tenant_id'],
                    'order_details_id' => $od->id,
                    'product_extra_id' => $product_extra_id,
                    'unit_price' => PricingService::instance()->getRetailPrice($productExtra),
                    'display_name' => $productExtra->name,
                    'qty' => 1,
                ]);
            }
        }
    }
}
