<?php

namespace App\Filament\Tenant\Resources\OrderResource\Pages;

use App\Filament\Tenant\Resources\OrderResource;
use App\Models\AdditionalCost;
use App\Models\AdditionalCostType;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Services\PricingService;
use Filament\Resources\Pages\EditRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class EditOrder extends EditRecord
{
    protected static string $resource = OrderResource::class;

    protected function getFormActions(): array
    {
        if ($this->record->status === Order::$STATUS_COMPLETED or $this->record->status === Order::$STATUS_CANCELLED) {
            $this->form->disabled();
            return [];
        }
        return parent::getFormActions();
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        unset($data['details']);
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    protected function afterSave(): void
    {
        $this->saveItems($this->data);
        $this->record->refresh();

        //sync invoice items
        $this->syncInvoiceItems();
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
//        "tenant_id" => 1
//      "user_id" => 3
//      "max_qty" => 10
//      "item_id" => 3
//      "item_type" => "App\Models\ProductVariant"
//      "unit_price" => "870.00"
//      "discount" => 0
//      "tax_percent" => null
//      "barcode_search_result_unit_id" => null
//      "barcode_search_result_product_id" => null
//      "product_id" => "1"
//      "unit_id" => "22"
//      "extras" => null
//      "qty" => 10
//      "price" => "8700.00"
//      "tax" => 1305

        $details = [];
        foreach ($this->record->details as $detail) {

            $unit_id = null;

            if ($detail->item instanceof Product)
                $product_id = $detail->item_id;

            if ($detail->item instanceof ProductVariant) {
                $product_id = $detail->item->product->id;
                $unit_id = $detail->item->unit_id;
            }

            $details[Str::uuid()->toString()] = [
                'id' => $detail->id,
                "tenant_id" => $detail->tenant_id,
                "user_id" => $detail->user_id,
                "max_qty" => 1000,
                "item_id" => $detail->item_id,
                "item_type" => $detail->item_type,
                "unit_price" => number_format($detail->unit_price, currency_decimals(), '.', ''),
                "discount" => number_format($detail->discount, currency_decimals(), '.', ''),
//                "tax_percent" => isset($detail['tax_profile_data']) ? $detail['tax_profile_data']['percent'] : null,
                "barcode_search_result_unit_id" => null,
                "barcode_search_result_product_id" => null,
                "product_id" => $product_id,
                "unit_id" => $unit_id,
                'product_extras_ids' => $detail->orderDetailsExtras->pluck('product_extra_id')->toArray(),
                "extras" => implode(', ', $detail->orderDetailsExtras->pluck('productExtra.extra')->pluck('name')->toArray()),
                "qty" => $detail->qty,
                'display_name' => $detail->item->name,
                "price" => number_format($detail->qty * $detail->unit_price, currency_decimals(), '.', ''),
                "tax" => number_format($detail->tax, currency_decimals(), '.', ''),
            ];
        }

        $data['details'] = $details;
//        dd($details);

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function saveItems($data)
    {
        foreach ($data['details'] as $index => $detail) {

            $taxProfile = null;

            $item = app()->make($detail['item_type'])->where('id', $detail['item_id'])->first();

            if ($item instanceof Product) {
                $taxProfile = $item->taxProfile;
            }

            if ($item instanceof ProductVariant) {
                $taxProfile = $item->product->taxProfile;
            }

            if ($taxProfile)
                $taxProfile->load('taxes');

            $orderDetail = OrderDetail::findOrFail($detail['id']);

            $orderDetail->update([
                'tenant_id' => $detail['tenant_id'],
                'order_id' => $this->record->id,
                'user_id' => auth()->id(),
                'item_id' => $detail['item_id'],
                'item_type' => $detail['item_type'],
                'unit_price' => $detail['unit_price'],
                'discount' => 0,
                'tax' => $detail['tax'],
                'qty' => $detail['qty'],
                'taken_qty' => 0,
                'cancelled' => 0,
                'tax_profile_data' => $taxProfile ? $taxProfile->toArray() : null,
            ]);

            $orderDetail->orderDetailsExtras()->delete();

            foreach ($detail['product_extras_ids'] ?? [] as $product_extra_id) {

                $productExtra = ProductExtra::with(['lastPrice', 'extra'])->findOrFail($product_extra_id);

                $orderDetail->orderDetailsExtras()->create([
                    'tenant_id' => $detail['tenant_id'],
                    'order_details_id' => $orderDetail->id,
                    'product_extra_id' => $product_extra_id,
                    'unit_price' => PricingService::instance()->getRetailPrice($productExtra),
                    'display_name' => $productExtra->name,
                    'qty' => 1,
                ]);
            }
        }
    }

    protected function syncInvoiceItems()
    {
        foreach ($this->record->invoice->items as $item) {
            $hasItem = $this->record->details->where('id', $item->order_details_id)->first();

            if (!$hasItem) {
                $item->delete();
            }
        }

        foreach ($this->record->details as $detail) {

            $invItem = $this->record->invoice->items()->firstWhere('order_details_id', $detail->id);

            if (!$invItem)
                throw new \Exception("Invoice item not found");

            $invItem->update([
                'qty' => $detail->qty,
                'price' => $detail->unit_price,
                'discount' => $detail->discount,
                'tax_profile_id' => isset($detail['tax_profile_data']) ? ($detail['tax_profile_data']['id'] ?? null) : null,
            ]);
        }

        $costTypeDelivery = AdditionalCostType::firstOrCreate([
            'name' => "توصيل/شحن"
        ], [
            'name' => "توصيل/شحن",
            'tenant_id' => filament()->getTenant()->id,
        ]);

        //sync additional cost
        $order = $this->record;
        $invoice = $order->invoice;
        $invAdditionalCost = AdditionalCost::where('meta->type', 'delivery_fees')->where('item_type', Invoice::class)->where('item_id', $invoice->id)->first();
        $invAdditionalCost->update([
            'cost' => $order->delivery,
        ]);
    }
}
