<?php

    namespace App\Filament\Admin\Resources\AdminResource\Pages;

    use App\Filament\Admin\Resources\AdminResource;
    use App\Models\User;
    use App\Services\RoleService;
    use Filament\Notifications\Notification;
    use Filament\Pages\Actions;
    use Filament\Resources\Pages\CreateRecord;
    use Illuminate\Support\Facades\Hash;
    use Spatie\Permission\Models\Role;

    class CreateAdmin extends CreateRecord
    {
        protected static string $resource = AdminResource::class;

        protected function mutateFormDataBeforeCreate(array $data): array
        {
            if (array_key_exists('password_confirmation', $data)) {
                unset($data['password_confirmation']);
            }

            if (Hash::needsRehash($data['password'])) {
                $data['password'] = bcrypt($data['password']);
            }

            return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
        }

    }
