<?php

namespace App\Filament\Tenant\Resources\Acc1Resource\Pages;

use App\Filament\Tenant\Pages\Settings;
use App\Filament\Tenant\Resources\Acc1Resource;
use Filament\Actions\CreateAction;
use Filament\Resources\Pages\ManageRecords;

class ManageAcc1s extends ManageRecords
{
    protected static string $resource = Acc1Resource::class;

    public function getBreadcrumbs(): array
    {
        return array_merge([
            Settings::getUrl() => __('fields.settings'),
            Acc1Resource::getUrl() => __('fields.level_1')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }


    protected function getActions(): array
    {
        return [
//            CreateAction::make(),
        ];
    }

    protected function getTableBulkActions(): array
    {
        return [];
    }
}
