<?php

namespace App\Filament\Tenant\Resources\ReceiptVoucherResource\Pages;

use App\Filament\Tenant\Resources\ReceiptVoucherResource;
use App\Models\Invoice;
use App\Models\Op;
use App\Models\OpType;
use App\Services\AccountingService;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreateReceiptVoucher extends CreateRecord
{
    protected static string $resource = ReceiptVoucherResource::class;


    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }
    public function mount(): void
    {
        parent::mount();

        $invoice_id = request('invoice_id', null);

        if ($invoice_id) {
            $inv = Invoice::with('supplier.acc4')->findOrFail($invoice_id);

            $this->form->fill([
                'no' => generate_receipt_voucher(),
                'user_id' => auth()->id(),
                'date' => now(),
                'for' => "customer",
                'acc4_code' => $inv->customer->acc4->code,
                'invoice_id' => $inv->id,
            ]);
        }else{
            $this->form->fill([
                'no' => generate_receipt_voucher(),
                'user_id' => auth()->id(),
                'date' => now(),
                'for' => "customer",
                'acc4_code' => null,
                'invoice_id' => null,
            ]);
        }

    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        unset($data['payments']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function getPaymentsAmount()
    {
        $paymentsAmount = 0;
        foreach ($this->data['payments'] ?? [] as $item)
        {
            $amount = $item['amount'] ?? 0;
            $paymentsAmount += $amount;
        }
        return $paymentsAmount;
    }

    protected function beforeCreate()
    {
        if($this->data['invoice_id'])
        {
            $invoice = Invoice::with(['salesPayments'])->findOrFail($this->data['invoice_id']);

            $totalToPay = $invoice->getItemsCost(true, true, true);

            if($this->getPaymentsAmount() > $totalToPay)
            {
                fns()->sendWarning(__("fields.payments_are_bigger_than_invoice_amount"));
                $this->halt();
            }
        }
    }

    public function create(bool $another = false): void
    {
        $this->authorizeAccess();

        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        try {

            DB::beginTransaction();

            $data = $this->mutateFormDataBeforeCreate($data);

            $this->callHook('beforeCreate');

            $this->record = $this->handleRecordCreation($data);

            $this->form->model($this->getRecord())->saveRelationships();

            $this->record->refresh();

            if ($this->record->invoice and $this->record->invoice->total_unpaid == 0 and
                $this->record->invoice->order and $this->record->invoice->order->paid_date === null) {

                $this->record->invoice->order->update(['paid_date' => now()]);
            }

            foreach ($this->record->payments as $payment) {
                if (!$payment->transaction_completed) {
                    $op = $payment->debitAccount->acc3_code = 1227 ? make_bank_transfer_receipt_voucher_op() :  make_cash_receipt_voucher_op();

                    $accService = new AccountingService();

                    $accService
                        ->setUp(
                            $op->id,
                            now(),
                            main_currency_iso_code(),
                            generate_double_entry_transaction_id(),
                            $payment->amount,
                            null,
                            $payment->statement,
                            $payment->statement,
                            $this->record->invoice_id,
                        )->make($payment->credit_acc4_code, $payment->debit_acc4_code)
                        ->finish();

                    $payment->update(['transaction_completed' => 1]);

//                    fns()->sendSuccess("Transaction completed");
                } else {
//                    fns()->sendWarning("Transaction skipped");
                }
            }

            $this->callHook('afterCreate');

            DB::commit();

        } catch (Halt $exception) {
            DB::rollBack();
            return;
        } catch (ValidationException $exception) {
            DB::rollBack();
            return;
        } catch (\Throwable $exception) {
            DB::rollBack();
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            dd($exception);
            $this->halt();
        }

        $this->getCreatedNotification()?->send();

        if ($another) {
            // Ensure that the form record is anonymized so that relationships aren't loaded.
            $this->form->model($this->getRecord()::class);
            $this->record = null;

            $this->fillForm();

            return;
        }

        $redirectUrl = $this->getRedirectUrl();

        if (FilamentView::hasSpaMode()) {
            $this->redirect($redirectUrl, navigate: is_app_url($redirectUrl));
        } else {
            $this->redirect($redirectUrl);
        }

    }

    public function afterCreate()
    {

    }
}
