<?php

namespace App\Filament\Tenant\Resources\ReceiptVoucherResource\Pages;

use App\Filament\Tenant\Resources\ReceiptVoucherResource;
use App\Models\Invoice;
use App\Models\Op;
use App\Models\OpType;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreateReceiptVoucher extends CreateRecord
{
    protected static string $resource = ReceiptVoucherResource::class;

    public $invoice_id, $order_id;

    public function mount(): void
    {
        parent::mount();

        $this->invoice_id = request('invoice_id', null);
        $this->order_id = request('order_id', null);

        if ($this->invoice_id) {
            $inv = Invoice::findOrFail($this->invoice_id);

            $this->form->fill([
                'no' => generate_receipt_voucher(),
                'user_id' => auth()->id(),
                'date' => now(),
                'for' => $inv->for,
                'debit_acc4_code' => $inv->getDebitAccountCode(),
                'supplier_id' => $inv->supplier_id,
                'customer_id' => $inv->customer_id,
                'invoice_id' => $inv->id,
                'received_invoice_id' => $this->invoice_id,
                'received_order_id' => $this->order_id,
            ]);
        }

    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['op_id'] = make_cash_receipt_voucher_op()->id;
        $data['invoice_id'] = $this->invoice_id;
        unset($data['payments']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function getPaymentsAmount()
    {
        $paymentsAmount = 0;
        foreach ($this->data['payments'] ?? [] as $item)
        {
            $amount = $item['amount'] ?? 0;
            $paymentsAmount += $amount;
        }
        return $paymentsAmount;
    }

    protected function beforeCreate()
    {
        if($this->invoice_id)
        {
            $invoice = Invoice::with(['salesPayments'])->findOrFail($this->invoice_id);

            $totalToPay = $invoice->getItemsCost(true, true, true);

            if($this->getPaymentsAmount() > $totalToPay)
            {
                fns()->sendWarning(__("fields.payments_are_bigger_than_invoice_amount"));
                $this->halt();
            }
        }
    }

    public function create(bool $another = false): void
    {
        $this->authorizeAccess();

        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        try {

            DB::beginTransaction();

            $data = $this->mutateFormDataBeforeCreate($data);

            $this->callHook('beforeCreate');

            $this->record = $this->handleRecordCreation($data);

            $this->form->model($this->getRecord())->saveRelationships();

            $this->callHook('afterCreate');

            DB::commit();

        } catch (Halt $exception) {
            DB::rollBack();
            return;
        } catch (ValidationException $exception) {
            DB::rollBack();
            return;
        } catch (\Throwable $exception) {
            DB::rollBack();
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            dd($exception);
            $this->halt();
        }

        $this->getCreatedNotification()?->send();

        if ($another) {
            // Ensure that the form record is anonymized so that relationships aren't loaded.
            $this->form->model($this->getRecord()::class);
            $this->record = null;

            $this->fillForm();

            return;
        }

        $redirectUrl = $this->getRedirectUrl();

        if (FilamentView::hasSpaMode()) {
            $this->redirect($redirectUrl, navigate: is_app_url($redirectUrl));
        } else {
            $this->redirect($redirectUrl);
        }

    }

    public function afterCreate()
    {

    }
}
