<?php

namespace App\Filament\Tenant\Resources\ReceiptVoucherResource\Pages;

use App\Filament\Tenant\Resources\ReceiptVoucherResource;
use App\Models\Invoice;
use App\Models\Supplier;
use App\Services\AccountingService;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Filament\Support\Exceptions\Halt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EditReceiptVoucher extends EditRecord
{
    protected static string $resource = ReceiptVoucherResource::class;

    protected function getActions(): array
    {
        return [
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        if ($this->record->invoice) {
//            $data['date'] = $this->record->created_at->format('d/m/Y');
            $data['for'] = $this->record->invoice ? "invoice" : $this->record->invoice->for;
            $data['supplier_id'] = $this->record->invoice->supplier_id;
            $data['customer_id'] = $this->record->invoice->customer_id;
            $data['invoice_id'] = $this->record->invoice->id;


            $payments = [];

            foreach ($this->record->invoice->salesPayments as $payment) {
                $payments[Str::random()] = [
                    'id' => $payment->id,
                    'method' => $payment->method,
                    'date' => $payment->date,
                    'amount' => $payment->amount,
                    'statement' => $payment->statement,
                    'user_id' => $payment->user_id,
                    'currency_iso_code' => $payment->currency_iso_code,
                ];
            }

            $data['payments'] = $payments;

        }

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function getPaymentsAmount()
    {
        $paymentsAmount = 0;
        foreach ($this->data['payments'] ?? [] as $item) {
            $amount = $item['amount'] ?? 0;
            $paymentsAmount += $amount;
        }
        return $paymentsAmount;
    }

    protected function beforeSave(): void
    {
        if ($this->record->invoice) {
            $totalToPay = $this->record->invoice->getItemsCost(true, true, true);

            if ($this->getPaymentsAmount() > $totalToPay) {
                fns()->sendWarning(__("fields.payments_are_bigger_than_invoice_amount"));
                $this->halt();
            }
        }
    }

    protected  function afterSave()
    {
        try {

            DB::beginTransaction();

            foreach ($this->record->payments as $payment) {
                if (!$payment->transaction_completed) {
                    $op = make_cash_receipt_voucher_op();

                    $accService = new AccountingService();

                    $accService
                        ->setUp(
                            $op->id,
                            now(),
                            main_currency_iso_code(),
                            generate_double_entry_transaction_id(),
                            $payment->amount,
                            null,
                            $payment->statement,
                            $payment->statement,
                            $this->record->invoice_id,
                        )->make($this->record->credit_acc4_code, $this->record->debit_acc4_code)
                        ->finish();

                    $payment->update(['transaction_completed' => 1]);

//                    fns()->sendSuccess("Transaction completed");
                } else {
//                    fns()->sendWarning("Transaction skipped");
                }
            }

            DB::commit();

        } catch (\Exception $exception) {
            DB::rollBack();
            fns()->sendDanger("Transaction failed");
        }

    }
}
