<?php

namespace App\Filament\Tenant\Resources\ReceiptVoucherResource\Pages;

use App\Filament\Tenant\Resources\ReceiptVoucherResource;
use App\Models\Invoice;
use App\Models\Supplier;
use App\Services\AccountingService;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Filament\Support\Exceptions\Halt;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class EditReceiptVoucher extends EditRecord
{
    protected static string $resource = ReceiptVoucherResource::class;

    protected function getActions(): array
    {
        return [
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        if ($this->record->invoice) {
            $payments = [];

            foreach ($this->record->invoice->salesPayments as $payment) {
                $payments[Str::random()] = [
                    'id' => $payment->id,
                    'date' => $payment->date,
                    'amount' => $payment->amount,
                    'statement' => $payment->statement,
                    'user_id' => $payment->user_id,
                ];
            }
            $data['payments'] = $payments;
        }

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function getPaymentsAmount()
    {
        $paymentsAmount = 0;
        foreach ($this->data['payments'] ?? [] as $item) {
            $amount = $item['amount'] ?? 0;
            $paymentsAmount += $amount;
        }
        return $paymentsAmount;
    }

    protected function beforeSave(): void
    {
        if ($this->record->invoice) {
            $totalToPay = $this->record->invoice->getItemsCost(true, true, true);

            if ($this->getPaymentsAmount() > $totalToPay) {
                fns()->sendWarning(__("fields.payments_are_bigger_than_invoice_amount"));
                $this->halt();
            }
        }
    }

    protected function afterSave()
    {
        try {

            $this->record->refresh();

            DB::beginTransaction();

            //update order paid date
            if ($this->record->invoice and $this->record->invoice->total_unpaid == 0 and
                 $this->record->invoice->order and $this->record->invoice->order->paid_date === null) {

                $this->record->invoice->order->update(['paid_date' => now()]);
            }

            foreach ($this->record->payments as $payment) {
                if (!$payment->transaction_completed) {
                    $op = $payment->debitAccount->acc3_code = 1227 ? make_bank_transfer_receipt_voucher_op() :  make_cash_receipt_voucher_op();

                    $accService = new AccountingService();

                    $accService
                        ->setUp(
                            $op->id,
                            now(),
                            main_currency_iso_code(),
                            generate_double_entry_transaction_id(),
                            $payment->amount,
                            null,
                            $payment->statement,
                            $payment->statement,
                            $this->record->invoice_id,
                        )->make($payment->credit_acc4_code, $payment->debit_acc4_code)
                        ->finish();

                    $payment->update(['transaction_completed' => 1]);

//                    fns()->sendSuccess("Transaction completed");
                } else {
//                    fns()->sendWarning("Transaction skipped");
                }
            }

            DB::commit();

        } catch (\Exception $exception) {
            DB::rollBack();
            report($exception);
            fns()->sendDanger("Transaction failed");
        }

    }
}
