<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Http\Exceptions\HttpResponseException;

class BaseRequest extends FormRequest
{

    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return false;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
        ];
    }

    protected function failedAuthorization()
    {
        //parent::failedAuthorization(); // TODO: Change the autogenerated stub
        abort(403);
    }


    protected function failedValidation(Validator $validator)
    {
        $errors = [];
        foreach ($validator->getMessageBag()->keys() as $key){
            $msg = $validator->getMessageBag()->get($key)[0] ?? 'Invalid input.';
            $errors[$key] = str($msg)->replace([' id'], '', false)->value();
        }
        throw new HttpResponseException(response()->json(
            [
                'statusCode' => 422,
                'statusText' => "Validation error",
                'message' => "Validation error",
                'data' => [],
                'filters' => [],
                'errors' => $errors,
                'debug' => [],
                'locale' => config('app.locale'),
            ], 422));


        //parent::failedValidation($validator); // TODO: Change the autogenerated stub
    }
}
