<?php

namespace App\Filament\Admin\Resources\PlanResource\Pages;

use App\Filament\Admin\Resources\PlanResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditPlan extends EditRecord
{
    use EditRecord\Concerns\Translatable;

    protected static string $resource = PlanResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\LocaleSwitcher::make(),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['unlimited_companies'] = $data['max_allowed_companies'] == -1;
        $data['unlimited_purchase_invoices'] = $data['max_allowed_purchase_invoices'] == -1;
        $data['unlimited_sales_invoices'] = $data['max_allowed_sales_invoices'] == -1;
        $data['restrict_account_after_period'] = $data['restrict_account_after_days'] > 0;


        return parent::mutateFormDataBeforeFill($data);
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if(!array_key_exists('max_allowed_companies', $data))
            $data['max_allowed_companies'] = -1; //unlimited

        if(!array_key_exists('max_allowed_purchase_invoices', $data))
            $data['max_allowed_purchase_invoices'] = -1; //unlimited

        if(!array_key_exists('max_allowed_sales_invoices', $data))
            $data['max_allowed_sales_invoices'] = -1; //unlimited

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
