<?php

namespace App\Filament\Tenant\Resources\TaxProfileResource\Pages;

use App\Filament\Tenant\Pages\CustomSettings;
use App\Filament\Tenant\Pages\Settings;
use App\Filament\Tenant\Resources\TaxProfileResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListTaxProfiles extends ListRecords
{
    protected static string $resource = TaxProfileResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    public function getBreadcrumbs(): array
    {
        return array_merge([
            CustomSettings::getUrl() => __('fields.settings')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }
}
