<?php

namespace App\Filament\Tenant\Resources\PaymentVoucherResource\Pages;

use App\Filament\Tenant\Resources\PaymentVoucherResource;
use App\Models\Invoice;
use App\Services\AccountingService;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class CreatePaymentVoucher extends CreateRecord
{
    protected static string $resource = PaymentVoucherResource::class;

    public $invoice_id;

    public function mount(): void
    {
        parent::mount();

        $this->invoice_id = request('invoice_id', null);

        if ($this->invoice_id) {
            $inv = Invoice::findOrFail($this->invoice_id);

            $this->form->fill([
                'no' => generate_payment_voucher(),
                'user_id' => auth()->id(),
                'date' => now(),
                'for' => $inv->for,
                'debit_acc4_code' => $inv->getDebitAccountCode(),
                'supplier_id' => $inv->supplier_id,
                'customer_id' => $inv->customer_id,
                'invoice_id' => $inv->id,
                'received_invoice_id' => $this->invoice_id,
            ]);
        }

    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['op_id'] = make_cash_receipt_voucher_op()->id;
        $data['invoice_id'] = $this->invoice_id;
        $data['supplier_id'] = Invoice::find($this->invoice_id)?->supplier_id;
        unset($data['payments']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function getPaymentsAmount()
    {
        $paymentsAmount = 0;
        foreach ($this->data['payments'] ?? [] as $item)
        {
            $amount = $item['amount'] ?? 0;
            $paymentsAmount += $amount;
        }
        return $paymentsAmount;
    }

    protected function beforeCreate()
    {
        if($this->invoice_id)
        {
            $invoice = Invoice::with(['payments'])->findOrFail($this->invoice_id);

            $totalToPay = $invoice->getItemsCost(true, true, true);

            if($this->getPaymentsAmount() > $totalToPay)
            {
                fns()->sendWarning(__("fields.payments_are_bigger_than_invoice_amount"));
                $this->halt();
            }
        }
    }

    public function create(bool $another = false): void
    {
        $this->authorizeAccess();

        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        try {
            DB::beginTransaction();

            $data = $this->mutateFormDataBeforeCreate($data);

            $this->createRecordAndCallHooks($data);

            DB::commit();

            /** @internal Read the DocBlock above the following method. */

        }catch (Halt $exception){
            DB::rollBack();
            return;
        } catch (ValidationException $exception){
            DB::rollBack();
            return;
        } catch (\Throwable $exception) {
            DB::rollBack();
            dd($exception);
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            $this->halt();
        }

        /** @internal Read the DocBlock above the following method. */
        $this->sendCreatedNotificationAndRedirect(shouldCreateAnotherInsteadOfRedirecting: $another);
    }

    protected function afterCreate(): void
    {
        try {

            DB::beginTransaction();

            foreach ($this->record->payments as $payment) {
                if (!$payment->transaction_completed) {
                    $op = make_cash_payment_voucher_op();

                    $accService = new AccountingService();

                    $accService
                        ->setUp(
                            $op->id,
                            now(),
                            main_currency_iso_code(),
                            generate_double_entry_transaction_id(),
                            $payment->amount,
                            null,
                            $payment->statement,
                            $payment->statement,
                            $this->record->invoice_id,
                        )->make($this->record->credit_acc4_code, $this->record->debit_acc4_code)
                        ->finish();

                    $payment->update(['transaction_completed' => 1]);

                    fns()->sendSuccess("Transaction completed");
                } else {
//                    fns()->sendWarning("Transaction skipped");
                }
            }

            DB::commit();

        } catch (\Exception $exception) {
            DB::rollBack();
            fns()->sendDanger("Transaction failed");
        }
    }
}
