<?php

    namespace App\Filament\Admin\Resources;

    use App\Filament\Admin\Resources\AppVersionResource\Pages;
    use App\Filament\Admin\Resources\AppVersionResource\RelationManagers;
    use App\Models\AppVersion;
    use Filament\Facades\Filament;
    use Filament\Forms;
    use Filament\Forms\Components\TextInput;
    use Filament\Notifications\Notification;
    use Filament\Resources\Resource;
    use Filament\Tables;
    use Illuminate\Database\Eloquent\Builder;
    use Illuminate\Database\Eloquent\Model;
    use Illuminate\Support\Facades\Cache;

    class AppVersionResource extends Resource
    {
        protected static ?string $model = AppVersion::class;

        protected static ?string $label = 'App Version';
        protected static ?string $pluralLabel = 'App Versions';
        protected static ?string $slug = 'app-versions';
        protected static ?string $navigationGroup = "Dev";
        protected static ?string $navigationIcon = 'heroicon-o-square-3-stack-3d';

        protected static ?int $navigationSort = -1;

        public static function getNavigationBadge(): ?string
        {
            return static::getModel()::count();
        }

        public function mount()
        {
            Notification::make()
                ->duration("Don`t forget to clear the latest version cache.")
                ->warning()
                ->send();
        }
        public static function form(Forms\Form $form): Forms\Form
        {
            return $form
                ->schema([
                    Forms\Components\Card::make([
                        Forms\Components\TextInput::make('version_code')
                            ->unique(ignorable: fn (?Model $record): ?Model => $record)
                            ->required()
                            ->default(1)
                            ->numeric(),
                        Forms\Components\Repeater::make('update_summary')
                            ->createItemButtonLabel('Add summary')
                            ->schema([
                            TextInput::make('summary')->required(),
                        ]),
                        Forms\Components\MarkdownEditor::make('description'),

                        Forms\Components\Checkbox::make("must_update")->inLine(),
                ]),
            ]);
    }

        public static function table(Tables\Table $table): Tables\Table
        {
            return $table
                ->columns([
                    Tables\Columns\TextColumn::make('version_code')->sortable()->searchable(),
                    Tables\Columns\IconColumn::make('must_update')->boolean(),
                    Tables\Columns\TextColumn::make('created_at')
                        ->dateTime('M j, Y')
                        ->sortable(),
                    Tables\Columns\TextColumn::make('updated_at')
                        ->dateTime('M j, Y')
                        ->sortable(),
                ])->pushActions([
                    Tables\Actions\Action::make('delete')
                        ->icon('heroicon-o-trash')
                        ->action(function (AppVersion $record) {
                            $record->delete();
                            Cache::forget('app-latest-version');
                            fns()->deleted();
                        })
                        ->requiresConfirmation()
                        ->color('danger'),
                ])
                ->filters([
                ]);
        }

        public static function getRelations(): array
        {
            return [
                //
            ];
        }

        public static function getPages(): array
        {
            return [
                'index' => Pages\ListAppVersions::route('/'),
                'create' => Pages\CreateAppVersion::route('/create'),
                'edit' => Pages\EditAppVersion::route('/{record}/edit'),
            ];
        }

        public static function getEloquentQuery(): Builder
        {
            return parent::getEloquentQuery()->orderByDesc('version_code'); // TODO: Change the autogenerated stub
        }

    }
