<?php

namespace App\Filament\Tenant\Resources\SupplyOrderResource\Pages;

use App\Filament\Tenant\Resources\SupplyOrderResource;
use App\Models\PriceOfferDetails;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Models\SupplyOrderDetails;
use App\Services\PricingService;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreateSupplyOrder extends CreateRecord
{
    protected static string $resource = SupplyOrderResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        unset($data['details']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function afterCreate(): void
    {
        $this->saveItems($this->record->id, $this->data);
    }

    protected function saveItems($supply_order_id, $data): void
    {
        foreach ($data['details'] as $index => $detail) {
            $sod = SupplyOrderDetails::create([
                'tenant_id' => $detail['tenant_id'],
                'supply_order_id' => $supply_order_id,
                'user_id' => auth()->id(),
                'item_id' => $detail['item_id'],
                'item_type' => $detail['item_type'],
                'qty' => $detail['qty'],
            ]);
        }
    }
}
