<?php

namespace App\Filament\Tenant\Resources\SupplyOrderResource\Pages;

use App\Filament\Tenant\Resources\SupplyOrderResource;
use App\Models\PriceOfferDetails;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Models\SupplyOrderDetails;
use App\Services\PricingService;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreateSupplyOrder extends CreateRecord
{
    protected static string $resource = SupplyOrderResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        unset($data['details']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    public function create(bool $another = false): void
    {
        $this->authorizeAccess();

        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        try {

            DB::beginTransaction();

            $data = $this->mutateFormDataBeforeCreate($data);

            $this->callHook('beforeCreate');

            $this->record = $this->handleRecordCreation($data);

            $this->form->model($this->getRecord())->saveRelationships();

            $this->saveItems($this->record->id, $this->data);

            DB::commit();

            $this->callHook('afterCreate');

        } catch (Halt $exception) {
            DB::rollBack();
            return;
        } catch (ValidationException $exception) {
            DB::rollBack();
            return;
        } catch (\Throwable $exception) {
            DB::rollBack();
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            $this->halt();
        }

        $this->getCreatedNotification()?->send();

        if ($another) {
            // Ensure that the form record is anonymized so that relationships aren't loaded.
            $this->form->model($this->getRecord()::class);
            $this->record = null;

            $this->fillForm();

            return;
        }

        $redirectUrl = $this->getRedirectUrl();

        if (FilamentView::hasSpaMode()) {
            $this->redirect($redirectUrl, navigate: is_app_url($redirectUrl));
        } else {
            $this->redirect($redirectUrl);
        }

    }


    protected function saveItems($supply_order_id, $data)
    {
        foreach ($data['details'] as $index => $detail) {
            $sod = SupplyOrderDetails::create([
                'tenant_id' => $detail['tenant_id'],
                'supply_order_id' => $supply_order_id,
                'user_id' => auth()->id(),
                'item_id' => $detail['item_id'],
                'item_type' => $detail['item_type'],
                'qty' => $detail['qty'],
            ]);
        }
    }
}
