<?php

namespace App\Filament\Tenant\Resources\SupplyOrderResource\Pages;

use App\Filament\Tenant\Resources\SupplyOrderResource;
use App\Models\PriceOfferDetails;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Models\SupplyOrderDetails;
use App\Services\PricingService;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class EditSupplyOrder extends EditRecord
{
    protected static string $resource = SupplyOrderResource::class;

    protected function getHeaderActions(): array
    {
        return [
        ];
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        unset($data['details']);
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    public function save(bool $shouldRedirect = true): void
    {
        $this->authorizeAccess();

        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        try {

            DB::beginTransaction();

            $data = $this->mutateFormDataBeforeSave($data);

            $this->callHook('beforeSave');

            $this->handleRecordUpdate($this->getRecord(), $data);

            $this->record->load(['details.item']);

            //save items
            $this->record->details()->delete();
            $this->saveItems($this->data);
            $this->record->refresh();

            DB::commit();

            $this->callHook('afterSave');

        } catch (Halt $exception) {
            DB::rollBack();
            return;
        } catch (ValidationException $exception) {
            DB::rollBack();
            return;
        } catch (\Throwable $exception) {
            DB::rollBack();
            dd($exception);
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            $this->halt();
        }

        $this->getSavedNotification()?->send();

        if ($shouldRedirect && ($redirectUrl = $this->getRedirectUrl())) {
            if (FilamentView::hasSpaMode()) {
                $this->redirect($redirectUrl, navigate: is_app_url($redirectUrl));
            } else {
                $this->redirect($redirectUrl);
            }
        }
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {

        $details = [];
        foreach ($this->record->details as $detail) {

            if ($detail->item instanceof Product)
                $product_id = $detail->item_id;

            if ($detail->item instanceof ProductVariant) {
                $product_id = $detail->item->product->id;
            }

            $details[Str::uuid()->toString()] = [
                'id' => $detail->id,
                "tenant_id" => $detail->tenant_id,
                "user_id" => $detail->user_id,
                "max_qty" => 100000,
                "item_id" => $detail->item_id,
                "item_type" => $detail->item_type,
                "product_id" => $product_id,
                "qty" => $detail->qty,
                'display_name' => $detail->item->name,
            ];
        }

        $data['details'] = $details;

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function saveItems($data)
    {
        foreach ($data['details'] as $index => $detail) {
            SupplyOrderDetails::create([
                'tenant_id' => $detail['tenant_id'],
                'supply_order_id' => $this->record->id,
                'user_id' => auth()->id(),
                'item_id' => $detail['item_id'],
                'item_type' => $detail['item_type'],
                'qty' => $detail['qty'],
            ]);

        }
    }
}
