<?php

namespace App\Filament\Tenant\Resources\WorkflowResource\Pages;

use App\Filament\Tenant\Resources\WorkflowResource;
use App\Services\ClassService;
use App\Services\WorkflowService;
use App\Workflows\Workflow;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\HtmlString;
use Spatie\Permission\Traits\HasRoles;

class EditWorkflow extends EditRecord
{
    protected static string $resource = WorkflowResource::class;

    protected function getActions(): array
    {
        return array_merge([
            Actions\Action::make('view_logs')
                ->color('danger')
                ->url(fn() => WorkflowResource::getUrl('viewLogs', ['record' => $this->record->id])),
        ]);
    }

    public function getHeading(): string|Htmlable
    {
        return "Workflow #" . $this->record->id;
    }

    public function getSubheading(): string|Htmlable|null
    {
        $sub_heading = "#" . $this->record->description;
        $actions = implode(', ', str_replace('-', ' ', $this->record->actions->pluck('action')->toArray()));;
        return new HtmlString($sub_heading . "<br> <strong>$actions</strong");
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['has_roles'] = (new WorkflowService())->modelHasRoles($data['model_type']);

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {

        if (array_key_exists('role_usage', $data) and $data['role_usage'] == "any-role") {
            $data['roles_names'] = null;
        }

        if($data['condition_type'] == "no-condition-is-required")
        {
            $this->record->conditions()->delete();
        }

        if(array_key_exists('role_usage', $data) and $data['role_usage'] == \App\Models\Workflow::ROLES_USAGE_SPECIFIED)
        {
            $model_supports_roles = (new ClassService())->classUses(HasRoles::class, $data['model_type']);
            if(!$model_supports_roles)
            {
                //role_back changes
                $data['role_usage'] = \App\Models\Workflow::ROLES_USAGE_NOT_SUPPORTED_BY_MODEL;
                $data['roles_names'] = null;
            }
        }

        if(!array_key_exists('role_usage', $data))
        {
            //role_back changes
            $data['role_usage'] = \App\Models\Workflow::ROLES_USAGE_NOT_SUPPORTED_BY_MODEL;
            $data['roles_names'] = null;
        }

        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

}
