<?php

namespace App\Filament\Tenant\Resources\WorkflowResource\Pages;

use App\Filament\Tenant\Resources\WorkflowResource;
use App\Services\WorkflowService;
use Filament\Actions\Action;
use Filament\Actions\EditAction;
use Filament\Resources\Pages\ViewRecord;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\HtmlString;

class ViewWorkflow extends ViewRecord
{
    protected static string $resource = WorkflowResource::class;


    public function getHeading(): string|Htmlable
    {
        return "Workflow #" . $this->record->id;
    }

    public function getSubheading(): string|Htmlable|null
    {
        $sub_heading = "#" . $this->record->description;
        $actions = implode(', ', str_replace('-', ' ', $this->record->actions->pluck('action')->toArray()));;
        return new HtmlString($sub_heading . "<br> <strong>$actions</strong");
    }

    protected function getActions(): array
    {
        return [
            EditAction::make(),
            Action::make()::make('view_logs')
                ->color('danger')
                ->url(fn() => WorkflowResource::getUrl('viewLogs', ['record' => $this->record->id])),
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['has_roles'] = (new WorkflowService())->modelHasRoles($data['model_type']);
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }
}
