<?php

namespace App\Filament\Tenant\Resources\PurchaseInvoiceStatusResource\Pages;

use App\Filament\Tenant\Resources\PurchaseInvoiceResource;
use App\Filament\Tenant\Resources\PurchaseInvoiceStatusResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListPurchaseInvoiceStatuses extends ListRecords
{
    protected static string $resource = PurchaseInvoiceStatusResource::class;

    public function getBreadcrumbs(): array
    {
        return array_merge([
            PurchaseInvoiceResource::getUrl() => __('fields.purchases_invoices')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }
}
