<?php

namespace App\Filament\Tenant\Resources\CouponResource\Pages;

use App\Filament\Tenant\Resources\CouponResource;
use App\Models\Coupon;
use Filament\Resources\Pages\CreateRecord;

class CreateCoupon extends CreateRecord
{
    protected static string $resource = CouponResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $type = $data["type"];
        if($type == Coupon::$TYPE_FIXED)
        {
            $data['value'] = $data['amount'];
            unset($data['amount']);
        }
        if($type == Coupon::$TYPE_PERCENT)
        {
            $data['value'] = $data['percent'];
            unset($data['percent']);
        }

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
