<?php

namespace App\Filament\Tenant\Resources\CouponResource\Pages;

use App\Filament\Tenant\Resources\CouponResource;
use App\Models\Coupon;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;

class EditCoupon extends EditRecord
{
    protected static string $resource = CouponResource::class;

    protected function getActions(): array
    {
        return [
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $type = $data["type"];
        if ($type == Coupon::$TYPE_FIXED) {
            $data['amount'] = $data['value'];
        }
        if ($type == Coupon::$TYPE_PERCENT) {
            $data['percent'] = $data['value'];
        }
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        $type = $data["type"];
        if ($type == Coupon::$TYPE_FIXED) {
            $data['value'] = $data['amount'];
            unset($data['amount']);
        }
        if ($type == Coupon::$TYPE_PERCENT) {
            $data['value'] = $data['percent'];
            unset($data['percent']);
        }
        if ($data['span'] == "unlimited-time") {
            $data['valid_until'] = null;
        }
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }
}
