<?php

namespace App\Filament\Tenant\Pages;

use App\Models\Setting;
use App\Services\CacheService;
use Filament\Actions\Action;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\View;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Pages\Concerns\InteractsWithFormActions;
use Filament\Pages\Page;
use Filament\Support\Enums\ActionSize;
use Illuminate\Contracts\Support\Htmlable;

class InvConfig extends Page implements HasForms
{
    use InteractsWithForms, InteractsWithFormActions;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.tenant.pages.inv-config';

    protected static bool $shouldRegisterNavigation = false;

    protected static ?string $slug = "settings/currency-and-invoices";

    public ?array $data = [];

    public function getTitle(): string|Htmlable
    {
        return __('fields.currency_and_invoices'); // TODO: Change the autogenerated stub
    }

    public function mount(): void
    {
        $this->form->fill();
    }

    protected function getFormSchema(): array
    {
        return [
            Section::make()
                ->statePath('data')
                ->schema(self::getFields())
                ->columns(2),
        ];
    }

    public function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label(__('fields.save'))
                ->action(function () {
                    $data = $this->form->getState();

                    foreach ($data['data'] ?? [] as $id => $value) {
                        Setting::find($id)->update(['value' => $value]);
                    }

                    CacheService::instance()->forget('settings');

                    $this->redirect(InvConfig::getUrl());

                    fns()->saved();
                })
        ];
    }

    public function getFields(): array
    {
        $fields = [];

        $settings = settings_by_group(['system']);

        foreach ($settings as $setting) {
            if ($setting->type == "text") {
                $field = TextInput::make($setting->id)
                    ->required($setting->is_required)
                    ->numeric($setting->is_numeric)
                    ->password($setting->is_password)
                    ->label($setting->display_name)
                    ->placeholder($setting->placeholder)
                    ->helperText($setting->helper_text)
                    ->rules($setting->rules ?? [])
                    ->default($setting->value);

                $fields[] = $field;
            }

            if ($setting->type == "options") {
                $fields[] = Select::make($setting->id)
                    ->searchable()
                    ->required($setting->is_required)
                    ->rules($setting->rules ?? [])
                    ->label($setting->display_name)
                    ->options($this->getSettingOptions($setting))
                    ->default($setting->value);
            }

            if ($setting->type == "rich-text") {
                $fields[] = RichEditor::make($setting->id)
                    ->rules($setting->rules ?? [])
                    ->label($setting->display_name)
                    ->default($setting->value);
            }
        }

        return $fields;
    }

    protected function getSettingOptions(Setting $setting)
    {
        if ($setting->options_cache_key) {
            if (str($setting->options_cache_key)->contains("currency_options")) {
            }
        }
        return $setting->options;
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('back')
                ->icon('heroicon-m-arrow-uturn-left')
                ->size(ActionSize::Large)
                ->url(CustomSettings::getUrl())
                ->iconButton()
        ];
    }

    public function getBreadcrumbs(): array
    {
        return array_merge([
            CustomSettings::getUrl() => __('fields.settings')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }
}
