<?php

namespace App\Filament\Tenant\Pages;

use App\Models\Setting;
use App\Services\CacheService;
use Filament\Actions\Action;
use Filament\Forms\Components\Fieldset;
use Filament\Forms\Components\Radio;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\SpatieMediaLibraryFileUpload;
use Filament\Forms\Components\Tabs;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\Toggle;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Get;
use Filament\Pages\Concerns\InteractsWithFormActions;
use Filament\Pages\Page;
use Filament\Support\Enums\ActionSize;
use Illuminate\Contracts\Support\Htmlable;

class Store extends Page implements HasForms
{
    use InteractsWithForms, InteractsWithFormActions;

    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.tenant.pages.store';

    protected static bool $shouldRegisterNavigation = false;

    protected static ?string $slug = "settings/store";

    public ?array $data = [];

    public function getTitle(): string|Htmlable
    {
        return __('fields.shop'); // TODO: Change the autogenerated stub
    }

    public function mount(): void
    {
        $this->data['store_title_ar'] = 'test';
        $tenant = get_tenant();
        $this->form->fill([
            "store_title_ar" => $tenant->store_title_ar,
            "store_bio_ar" => $tenant->store_bio_ar,
            "store_address_ar" => $tenant->store_address_ar,
            "store_working_hours_ar" => $tenant->store_working_hours_ar,
            "store_title_en" => $tenant->store_title_en,
            "store_bio_en" => $tenant->store_bio_en,
            "store_address_en" => $tenant->store_address_en,
            "store_working_hours_en" => $tenant->store_working_hours_en,
            "store_social_media_links" => $tenant->store_social_media_links,
            "store_enable_stock_tracking" => $tenant->store_enable_stock_tracking,
            "store_hide_out_of_stock_products" => $tenant->store_hide_out_of_stock_products,
            "store_enable_orders_tracking" => $tenant->store_enable_orders_tracking,
            "store_orders_tracking_mode" => $tenant->store_orders_tracking_mode,
            "store_orders_tracking_packaging_time_hours" => $tenant->store_orders_tracking_packaging_time_hours,
            "store_orders_tracking_delivery_time_hours" => $tenant->store_orders_tracking_delivery_time_hours,
            "store_terms_and_conditions" => $tenant->store_terms_and_conditions,
        ]);

        $arr = array([
            "store_title_ar" => $tenant->store_title_ar,
            "store_bio_ar" => $tenant->store_bio_ar,
            "store_address_ar" => $tenant->store_address_ar,
            "store_working_hours_ar" => $tenant->store_working_hours_ar,
            "store_title_en" => $tenant->store_title_en,
            "store_bio_en" => $tenant->store_bio_en,
            "store_address_en" => $tenant->store_address_en,
            "store_working_hours_en" => $tenant->store_working_hours_en,
            "store_social_media_links" => $tenant->store_social_media_links,
            "store_enable_stock_tracking" => $tenant->store_enable_stock_tracking,
            "store_hide_out_of_stock_products" => $tenant->store_hide_out_of_stock_products,
            "store_enable_orders_tracking" => $tenant->store_enable_orders_tracking,
            "store_orders_tracking_mode" => $tenant->store_orders_tracking_mode,
            "store_orders_tracking_packaging_time_hours" => $tenant->store_orders_tracking_packaging_time_hours,
            "store_orders_tracking_delivery_time_hours" => $tenant->store_orders_tracking_delivery_time_hours,
            "store_terms_and_conditions" => $tenant->store_terms_and_conditions,
        ]);

        $this->data = $arr[0];
    }

    protected function getFormSchema(): array
    {
        return [
            Section::make()
                ->statePath('data')
                ->schema([
                    Tabs::make('Tabs')
                        ->tabs([
                            Tabs\Tab::make(__('fields.arabic'))
                                ->schema([

                                    TextInput::make('store_title_ar')
                                        ->label(__('fields.store_title')),

                                    RichEditor::make('store_bio_ar')
                                        ->label(__('fields.store_bio'))
                                        ->columnSpanFull(),

                                    TextInput::make('store_address_ar')
                                        ->label(__('fields.store_address')),

                                    TextInput::make('store_working_hours_ar')
                                        ->label(__('fields.store_working_hours')),

                                ])->columns(3),
                            Tabs\Tab::make(__('fields.english'))
                                ->schema([

                                    TextInput::make('store_title_en')
                                        ->label(__('fields.store_title')),

                                    RichEditor::make('store_bio_en')
                                        ->label(__('fields.store_bio'))
                                        ->columnSpanFull(),

                                    TextInput::make('store_address_en')
                                        ->label(__('fields.store_address')),

                                    TextInput::make('store_working_hours_en')
                                        ->label(__('fields.store_working_hours')),
                                ]),

                        ])->columns(3),

                    Fieldset::make(__('fields.social_media_links'))->schema([

                        TextInput::make('store_social_media_links.facebook')
                            ->label(__('fields.social_label.facebook')),

                        TextInput::make('store_social_media_links.instagram')
                            ->label(__('fields.social_label.instagram')),

                        TextInput::make('store_social_media_links.twitter')
                            ->label(__('fields.social_label.twitter')),

                        TextInput::make('store_social_media_links.youtube')
                            ->label(__('fields.social_label.youtube')),

                        TextInput::make('store_social_media_links.snapchat')
                            ->label(__('fields.social_label.snapchat')),

                        TextInput::make('store_social_media_links.whatsapp')
                            ->label(__('fields.social_label.whatsapp')),

                    ]),

                    SpatieMediaLibraryFileUpload::make('cover')
                        ->label(__('fields.store_cover'))
                        ->image()
                        ->openable()
                        ->downloadable()
                        ->maxSize(4080)
                        ->disk('public')
                        ->collection('covers')
                        ->directory('covers'),

                    Toggle::make('store_enable_stock_tracking')
                        ->helperText(__('fields.store_enable_stock_tracking_hint'))
                        ->label(__('fields.store_enable_stock_tracking')),

                    Toggle::make('store_hide_out_of_stock_products')
                        ->label(__('fields.store_hide_out_of_stock_products')),

                    Fieldset::make()->schema([

                        Toggle::make('store_enable_orders_tracking')
                            ->live()
                            ->label(__('fields.store_enable_orders_tracking')),

                        Radio::make('store_orders_tracking_mode')
                            ->live()
                            ->visible(fn(Get $get) => $get('store_enable_orders_tracking') == true)
                            ->required()
                            ->options([
                                'manually' => __('fields.store_manually_change_orders_statuses'),
                                'automatic' => __('fields.store_automatically_change_orders_statuses'),
                            ])
                            ->label(__('fields.store_orders_tracking_mode')),

                        TextInput::make('store_orders_tracking_packaging_time_hours')
                            ->visible(fn(Get $get) => $get('store_enable_orders_tracking') == true and $get('store_orders_tracking_mode') == "automatic")
                            ->required()
                            ->numeric()
                            ->maxValue(500)
                            ->step(1)
                            ->extraInputAttributes(['min' => 1, 'max' => 500])
                            ->label(__('fields.store_orders_tracking_packaging_time_hours')),

                        TextInput::make('store_orders_tracking_delivery_time_hours')
                            ->visible(fn(Get $get) => $get('store_enable_orders_tracking') == true and $get('store_orders_tracking_mode') == "automatic")
                            ->required()
                            ->numeric()
                            ->maxValue(500)
                            ->step(1)
                            ->extraInputAttributes(['min' => 1, 'max' => 500])
                            ->label(__('fields.store_orders_tracking_delivery_time_hours')),

                    ])->columns(4),

                    RichEditor::make('store_terms_and_conditions')
                        ->label(__('fields.store_terms_and_conditions')),
                ]),
        ];
    }

    public function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label(__('fields.save'))
                ->action(function () {
                    get_tenant()->update($this->form->getState()['data']);
                    $this->redirect(Store::getUrl());
                    fns()->saved();
                })
        ];
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('back')
                ->icon('heroicon-m-arrow-uturn-left')
                ->size(ActionSize::Large)
                ->url(CustomSettings::getUrl())
                ->iconButton(),
        ];
    }

    public function getBreadcrumbs(): array
    {
        return array_merge([
            CustomSettings::getUrl() => __('fields.settings')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }
}
