<?php

namespace App\Filament\Tenant\Pages;

use Filament\Actions\Action;
use Filament\Pages\Page;
use Filament\Support\Enums\MaxWidth;
use Illuminate\Contracts\Support\Htmlable;

class Subscription extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    protected static string $view = 'filament.tenant.pages.subscription';

    protected static bool $shouldRegisterNavigation = false;

    public function getTitle(): string | Htmlable
    {
        return __('fields.subscription');
    }

    public function getHeading(): string|Htmlable
    {
        return __('fields.subscription');
    }

    public function getMaxContentWidth(): MaxWidth
    {
        return MaxWidth::Full;
    }

    protected function getHeaderActions(): array
    {
        return [
            Action::make('back')
                ->label(__('fields.subscription_back_to_settings'))
                ->icon('heroicon-m-arrow-uturn-right')
                ->color('gray')
                ->url(CustomSettings::getUrl()),
        ];
    }

    public function getBreadcrumbs(): array
    {
        return array_merge([
            CustomSettings::getUrl() => __('fields.settings')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }
}
