<?php

namespace App\Filament\Tenant\Pages;

use App\Models\User;
use App\Rules\InternationalPhoneRule;
use App\Rules\UniqueClientAttributeRule;
use App\Rules\UniqueItemAttributeRule;
use App\Services\SettingService;
use Filament\Actions\Action;
use Filament\Facades\Filament;
use Filament\Forms\Components\Checkbox;
use Filament\Forms\Components\ColorPicker;
use Filament\Forms\Components\Fieldset;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\Section;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Tabs;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Pages\Concerns\InteractsWithFormActions;
use Filament\Pages\Page;
use Filament\Support\Colors\Color;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\Str;

class TenantUserProfile extends Page implements HasForms
{
    use InteractsWithForms, InteractsWithFormActions;

    protected static string $view = 'filament.pages.profile';

    protected static ?string $navigationIcon = 'heroicon-o-user-circle';

    protected static ?string $slug = "t-profile";

    public $first_name, $second_name, $third_name, $fourth_name;

    public $email, $phone;

    public $current_password;

    public $new_password;

    public $new_password_confirmation;

    public $font, $primary_color, $enable_notifications, $enable_top_navigation;

    public $date_picker_format, $date_column_format;

    protected $user_id;

    public function mount()
    {
        $user = auth()->user();

        $this->user_id = $user->id;

        $this->form->fill([
            'first_name' => $user->first_name,
            'second_name' => $user->second_name,
            'third_name' => $user->third_name,
            'fourth_name' => $user->fourth_name,
            'email' => $user->email,
            'phone' => $user->phone,
            'font' => Filament::getCurrentPanel()->getFontFamily(),
            'primary_color' => user_setting('primary_color', "#e8d41b"),
            'enable_notifications' => (bool)user_setting('enable_notifications', true),
            'enable_top_navigation' => (bool)user_setting('enable_top_navigation', false),
            'date_picker_format' => user_setting('date_picker_format', "d/m/Y"),
            'date_column_format' => user_setting('date_column_format', "d/m/Y g:i a"),

        ]);

    }

    public static function shouldRegisterNavigation(array $parameters = []): bool
    {
        return false;
    }

    public function getTitle(): string|Htmlable
    {
        return __('fields.profile_and_preferences'); // TODO: Change the autogenerated stub
    }

    public function getSubheading(): string|Htmlable
    {
        return auth()->user()->full_name; // TODO: Change the autogenerated stub
    }

    protected function getFormSchema(): array
    {
        return [

            Tabs::make()
                ->persistTabInQueryString()
                ->schema([
                    Tabs\Tab::make('Account')
                        ->label(__('fields.account'))
                        ->icon('heroicon-o-user-circle')
                        ->schema([
                            Section::make(__('fields.general'))
                                ->columns(4)
                                ->schema([
                                    TextInput::make('first_name')
                                        ->label(__('fields.first_name'))
                                        ->required(),

                                    TextInput::make('second_name')
                                        ->label(__('fields.second_name'))
                                        ->required(),

                                    TextInput::make('third_name')
                                        ->label(__('fields.third_name')),

                                    TextInput::make('fourth_name')
                                        ->label(__('fields.fourth_name')),


                                    TextInput::make('phone')
                                        ->label(__('fields.phone'))
                                        ->columnSpan(2)
                                        ->rules(
                                            [
                                                new InternationalPhoneRule(false),
                                                new UniqueItemAttributeRule(User::class, 'phone', auth()->id(), true)
                                            ]
                                        )
                                        ->required(),

                                    TextInput::make('email')
                                        ->label(__('fields.email'))
                                        ->columnSpan(2)
                                        ->email()
                                        ->rules(
                                            [
                                                new UniqueItemAttributeRule(User::class, 'email', auth()->id(), true)
                                            ]
                                        )
                                        ->required(),

                                ]),
                            Section::make(__('fields.security'))
                                ->columns(2)
                                ->schema([
                                    TextInput::make('current_password')
                                        ->label(__('fields.current_password'))
                                        ->password()
                                        ->rules(['required_with:new_password'])
                                        ->currentPassword()
                                        ->autocomplete('off')
                                        ->columnSpan(1),
                                    Grid::make()
                                        ->schema([
                                            TextInput::make('new_password')
                                                ->label(__('fields.new_password'))
                                                ->password()
                                                ->rules(['confirmed'])
                                                ->autocomplete('new-password'),
                                            TextInput::make('new_password_confirmation')
                                                ->label(__('fields.new_password_confirmation'))
                                                ->password()
                                                ->rules([
                                                    'required_with:new_password',
                                                ])
                                                ->autocomplete('new-password'),
                                        ]),
                                ]),
                        ]),

                    Tabs\Tab::make(__('fields.appearance'))
                        ->label(__('fields.appearance'))
                        ->icon('heroicon-o-swatch')
                        ->schema([
                            Fieldset::make("General")
                                ->label(__('fields.general'))
                                ->schema([

                                    TextInput::make('font')
                                        ->label(__('fields.font'))
                                        ->hint("Google fonts")
                                        ->datalist([
                                            'Poppins',
                                            'Roboto',
                                            'Rubik',
                                            'Young Serif',
                                            'Gabarito',
                                            'Montserrat',
                                            'Cairo',
                                            'Inter',
                                        ]),

                                    ColorPicker::make('primary_color')
                                        ->required()
                                        ->label(__('fields.primary_color')),

                                    Checkbox::make("enable_notifications")
                                        ->label(__('fields.enable_notifications'))
                                        ->columnSpan(3),

                                    Checkbox::make("enable_top_navigation")
                                        ->label(__('fields.enable_top_navigation'))
                                        ->columnSpan(3),

                                ])
                        ]),

                    Tabs\Tab::make('Preferences')
                        ->label(__('fields.preferences'))
                        ->icon('heroicon-o-adjustments-vertical')
                        ->schema([
                            Section::make()->schema([
                                Select::make('date_picker_format')
                                    ->label(__('fields.date_picker_format'))
                                    ->required()
                                    ->options((new SettingService(\filament()->getTenant()?->id))->dateFormats()),
                                Select::make('date_column_format')
                                    ->label(__('fields.date_column_format'))
                                    ->required()
                                    ->options((new SettingService(\filament()->getTenant()?->id))->dateFormats()),
                            ])->columns(2)
                        ]),
                ]),
        ];
    }


    public function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label(__('fields.save'))
                ->action(function () {
                    $this->form->getState();

                    $state = array_filter([
                        'first_name' => $this->first_name,
                        'second_name' => $this->second_name,
                        'third_name' => $this->third_name,
                        'fourth_name' => $this->fourth_name,
                        'email' => $this->email,
                        'phone' => $this->phone,
                        'password' => $this->new_password ? \Hash::make($this->new_password) : null,
                    ]);

                    $user = auth()->user();

                    if ($state['email'] and $user->email != $state['email']) {
                        $state['email_verified_at'] = null;
                    }

                    if ($state['phone'] and str($user->phone)->remove('+')->value() != $state['phone']) {
                        $state['phone_verified_at'] = null;
                    }

                    $user->settings(
                        [
                            'font' => $this->font,
                            'primary_color' => $this->primary_color,
                            'enable_notifications' => $this->enable_notifications,
                            'enable_top_navigation' => $this->enable_top_navigation,
                            'date_picker_format' => $this->date_picker_format,
                            'date_column_format' => $this->date_column_format,
                        ]
                    );

                    $user->update($state);

                    if ($this->new_password) {
                        $this->updateSessionPassword($user);
                    }

                    $this->reset(['current_password', 'new_password', 'new_password_confirmation']);

                    $this->redirect(TenantUserProfile::getUrl());
//                    fns()->sendSuccess(implode(', ', \Route::current()->parameterNames()));
                    fns()->saved();
                })
        ];
    }

    protected function updateSessionPassword($user)
    {
        request()->session()->put([
            'password_hash_' . auth()->getDefaultDriver() => $user->getAuthPassword(),
        ]);
    }
}
