<?php

namespace App\Filament\Tenant\Resources\CategoryResource\Pages;

use App\Filament\MyActions\Pages\AddToFavourites;
use App\Filament\Tenant\Pages\Settings;
use App\Filament\Tenant\Resources\CategoryResource;
use Filament\Actions\CreateAction;
use Filament\Actions\LocaleSwitcher;
use Filament\Resources\Pages\ListRecords;

class ListCategories extends ListRecords
{
    use ListRecords\Concerns\Translatable;

    protected static string $resource = CategoryResource::class;

    protected function getHeaderActions(): array
    {
        return [
            AddToFavourites::make('fav')
                ->settingKey('fav.products_categories'),
            LocaleSwitcher::make(),
            CreateAction::make(),
        ];
    }

    protected function getHeaderWidgets(): array
    {
        return [
            \App\Filament\Tenant\Resources\CategoryResource\Widgets\CategoryOverview::class
        ];
    }

    protected function getTableBulkActions(): array
    {
        return [
            // ...
        ];
    }

    public function getBreadcrumbs(): array
    {
        return array_merge([
            Settings::getUrl() => __('fields.settings')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }
}
