<?php

namespace App\Filament\Tenant\Resources\PriceOfferResource\Pages;

use App\Filament\Tenant\Resources\PriceOfferResource;
use App\Models\Invoice;
use App\Models\Order;
use App\Models\OrderDetail;
use App\Models\PriceOfferDetails;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Models\TaxProfile;
use App\Services\PricingService;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreatePriceOffer extends CreateRecord
{
    protected static string $resource = PriceOfferResource::class;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    public function mount(): void
    {
        parent::mount();

        PriceOfferResource::ensureDefaultInvoiceLineOnCreate($this, 'details');
        PriceOfferResource::updateInvoicePropertiesFromLivewire($this);
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        unset($data['details']);
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function afterCreate(): void
    {
        $this->saveItems($this->record->id, $this->data);
    }

    protected function saveItems($price_offer_id, $data)
    {
        foreach ($data['details'] as $index => $detail) {
            $detail = PriceOfferResource::normalizeInlineProductRowForSave($detail);

            if (empty($detail['item_id'])) {
                continue;
            }

            $taxProfile = null;

            $item = app()->make($detail['item_type'])->where('id', $detail['item_id'])->first();

            if ($item instanceof Product) {
                $taxProfile = $item->taxProfile;
            }

            if ($item instanceof ProductVariant) {
                $taxProfile = $item->product->taxProfile;
            }

            if ($taxProfile)
                $taxProfile->load('taxes');

            $od = PriceOfferDetails::create([
                'tenant_id' => $detail['tenant_id'],
                'price_offer_id' => $price_offer_id,
                'user_id' => auth()->id(),
                'item_id' => $detail['item_id'],
                'item_type' => $detail['item_type'],
                'unit_price' => $detail['price'],
                'discount' => 0,
                'tax' => $detail['tax'] ?? 0,
                'tax_profile_id' => $detail['tax_profile_id'] ?? null,
                'tax_profile_data' => TaxProfile::find($detail['tax_profile_id'] ?? null)?->toArray(),
                'qty' => $detail['qty'],
            ]);

            foreach ($detail['product_extras_ids'] ?? [] as $product_extra_id) {

                $productExtra = ProductExtra::with(['lastPrice', 'extra'])->findOrFail($product_extra_id);

                $od->offerDetailsExtras()->create([
                    'tenant_id' => $detail['tenant_id'],
                    'price_offer_details_id' => $od->id,
                    'product_extra_id' => $product_extra_id,
                    'unit_price' => PricingService::instance()->getRetailPrice($productExtra),
                    'display_name' => $productExtra->name,
                    'qty' => 1,
                ]);
            }
        }
    }
}
