<?php

namespace App\Filament\Tenant\Resources\PriceOfferResource\Pages;

use App\Filament\Tenant\Resources\PriceOfferResource;
use App\Models\OrderDetail;
use App\Models\PriceOfferDetails;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Models\TaxProfile;
use App\Services\PricingService;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class EditPriceOffer extends EditRecord
{
    protected static string $resource = PriceOfferResource::class;

    protected function getHeaderActions(): array
    {
        return [
        ];
    }
    protected function mutateFormDataBeforeSave(array $data): array
    {
        unset($data['details']);
        return parent::mutateFormDataBeforeSave($data); // TODO: Change the autogenerated stub
    }

    protected function afterSave(): void
    {
        $this->record->load(['details', 'invoice']);

        //save items
        foreach ($this->record->details as $detail){
            $detail->offerDetailsExtras()->delete();
            $detail->delete();
        }
        $this->saveItems($this->data);
    }


    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['discount_option_overall'] = $this->record->discount_option == "overall";

        $details = [];
        foreach ($this->record->details as $detail) {

            $product = null;
            if ($detail->item instanceof Product){
                $product_id = $detail->item_id;
                $product = $detail->item;
            }
            if ($detail->item instanceof ProductVariant) {
                $product_id = $detail->item->product->id;
                $product = $detail->item->product;
            }

            $details[Str::uuid()->toString()] = [
                'id' => $detail->id,
                "tenant_id" => $detail->tenant_id,
                "user_id" => $detail->user_id,
                "max_qty" => 1000,
                "item_id" => $detail->item_id,
                "item_type" => $detail->item_type,
                "unit_price" => number_format($detail->unit_price, currency_decimals(), '.', ''),
                "discount" => number_format($detail->discount, currency_decimals(), '.', ''),
                "product_id" => $product_id,
                'product_extras_ids' => $detail->offerDetailsExtras->pluck('product_extra_id')->toArray(),
                'available_product_extras_ids' => $product->extras->pluck('id')->toArray(),
                'extras_total' => PricingService::instance()->getRetailPrices(ProductExtra::with('lastPrice')->findMany($detail->offerDetailsExtras->pluck('product_extra_id')->toArray())),
                "extras" => implode(', ', $detail->offerDetailsExtras->pluck('display_name')->toArray()),
                "qty" => $detail->qty,
                'display_name' => $detail->item->name,
                "price" => number_format($detail->unit_price, currency_decimals(), '.', ''),
                "tax" => number_format($detail->tax, currency_decimals(), '.', ''),
                'tax_profile_id' => $detail->tax_profile_id,
                'tax_profile_data' => TaxProfile::find($detail->tax_profile_id)?->toArray(),
                "sub_total" => number_format($detail->qty * $detail->price, currency_decimals(), '.', ''),
            ];
        }

        $data['details'] = $details;

        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function saveItems($data)
    {
        foreach ($data['details'] as $index => $detail) {

            $taxProfile = null;

            $item = app()->make($detail['item_type'])->where('id', $detail['item_id'])->first();

            if ($item instanceof Product) {
                $taxProfile = $item->taxProfile;
            }

            if ($item instanceof ProductVariant) {
                $taxProfile = $item->product->taxProfile;
            }

            if ($taxProfile)
                $taxProfile->load('taxes');

            $orderDetail = PriceOfferDetails::create([
                'tenant_id' => $detail['tenant_id'],
                'price_offer_id' => $this->record->id,
                'user_id' => auth()->id(),
                'item_id' => $detail['item_id'],
                'item_type' => $detail['item_type'],
                'unit_price' => $detail['price'],
                'discount' => $detail['discount'],
                'tax_profile_id' => $detail['tax_profile_id'] ?? null,
                'tax_profile_data' => TaxProfile::find($detail['tax_profile_id'] ?? null)?->toArray(),
                'tax' => $detail['tax'],
                'qty' => $detail['qty'],
            ]);

            foreach ($detail['product_extras_ids'] ?? [] as $product_extra_id) {

                $productExtra = ProductExtra::with(['lastPrice', 'extra'])->findOrFail($product_extra_id);

                $orderDetail->offerDetailsExtras()->create([
                    'tenant_id' => $detail['tenant_id'],
                    'price_offer_details_id' => $orderDetail->id,
                    'product_extra_id' => $product_extra_id,
                    'unit_price' => PricingService::instance()->getRetailPrice($productExtra),
                    'display_name' => $productExtra->name,
                    'qty' => 1,
                ]);
            }
        }
    }
}
