<?php

namespace App\Filament\Tenant\Resources\PurchaseInvoiceResource\Pages;

use App\Filament\Tenant\Resources\PurchaseInvoiceResource;
use App\Filament\Tenant\Resources\TaxProfileResource;
use App\Models\InvoiceItem;
use App\Models\InvoiceStatus;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreatePurchaseInvoice extends CreateRecord
{
    protected static string $resource = PurchaseInvoiceResource::class;

    protected function getHeaderActions(): array
    {
        return [
//            Action::make('tax_profiles')
//                ->label(__('fields.tax_profiles'))
//                ->color('primary')
//                ->url(fn() => TaxProfileResource::getUrl(), true),
        ];
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    protected function beforeCreate(): void
    {
        //check for duplicates
        foreach ($this->data['items'] ?? [] as $item)
        {
            $sameDetails = collect($this->data['items'] ?? [])
                ->where('product_id', $item['product_id'])
                ->where('unit_id', $item['unit_id'])
                ->count();

            if($sameDetails > 1){
                fns()->sendWarning("Duplicate product/unit.");
                $this->halt();
            }
        }
    }

    public function create(bool $another = false): void
    {
        $this->authorizeAccess();

        $this->callHook('beforeValidate');

        $data = $this->form->getState();

        $this->callHook('afterValidate');

        try {
            DB::beginTransaction();

            $data = $this->mutateFormDataBeforeCreate($data);

            $this->createRecordAndCallHooks($data);

            DB::commit();

            /** @internal Read the DocBlock above the following method. */

        }catch (Halt $exception){
            DB::rollBack();
            return;
        } catch (ValidationException $exception){
            DB::rollBack();
            return;
        } catch (\Throwable $exception) {
            DB::rollBack();
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            $this->halt();
        }

        /** @internal Read the DocBlock above the following method. */
        $this->sendCreatedNotificationAndRedirect(shouldCreateAnotherInsteadOfRedirecting: $another);
    }

}
