<?php

namespace App\Filament\Tenant\Resources\PurchaseInvoiceResource\Pages;

use App\Filament\Tenant\Resources\PurchaseInvoiceResource;
use App\Filament\Tenant\Resources\TaxProfileResource;
use App\Models\Invoice;
use App\Models\InvoiceItem;
use App\Models\InvoiceStatus;
use App\Models\Product;
use App\Models\ProductVariant;
use App\Models\SupplyOrder;
use App\Services\PricingService;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreatePurchaseInvoice extends CreateRecord
{
    protected static string $resource = PurchaseInvoiceResource::class;

    protected $supply_order_id;

    protected function getRedirectUrl(): string
    {
        return $this->getResource()::getUrl('index');
    }

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        $this->supply_order_id = request('supply_order_id', null);

        $supplyOder = SupplyOrder::with('details.item')->find($this->supply_order_id);

        if ($supplyOder) {

            $items = [];

            foreach ($supplyOder->details as $detail) {

                $items[Str::uuid()->toString()] = [
                    'tenant_id' => $detail->tenant_id,
                    'product_id' => $detail->item_type == Product::class ? $detail->item_id : ProductVariant::find($detail->item_id)->product_id,
                    'product_variant_id' => $detail->item_type == ProductVariant::class ? $detail->item_id : null,
                    'item_id' => $detail->item_id,
                    'item_type' => $detail->item_type,
                    'name' => $detail->item->name,
                    'qty' => $detail->qty,
                    'price' => null,
                    'tax' => PricingService::instance()->getTaxAmount($detail->item instanceof Product ? $detail->item : $detail->item->product, $detail->unit_price, $detail->qty),
                    'discount' => 0,
                    'tax_profile_id' => null,
                    'tax_profile_data' => null,
                ];
            }

            $this->form->fill([
                'no' =>  generate_invoice_no(),
                'date' => now(),
                'type' => 'purchases',
                'for' => 'supplier',
                'status' => 'purchase_order',
                'discount_option' => 'per-item',
                'supply_order_id' => $supplyOder->id,
                'supplier_id' => $supplyOder->supplier_id,
                'items' => $items,
            ]);

            $this->data['items'] = $items;
//            dd($this);
        }
    }

    protected function getHeaderActions(): array
    {
        return [
        ];
    }
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        if(Invoice::firstWhere('no', $this->data['no'])){
            $data['no'] = generate_invoice_no();
        }
        return $data;
    }
}
