<?php

namespace App\Filament\Tenant\Resources\PurchaseInvoiceResource\Pages;

use App\Filament\Tenant\Resources\PurchaseInvoiceResource;
use App\Models\InvoiceItem;
use App\Models\InvoiceStatus;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\QueryException;
use Illuminate\Support\Facades\DB;
use function Filament\Support\is_app_url;

class CreatePurchaseInvoice extends CreateRecord
{
    protected static string $resource = PurchaseInvoiceResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $data['no'] = generate_invoice_no();
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }

    public function create(bool $another = false): void
    {
        $this->authorizeAccess();

        try {
            DB::beginTransaction();

            $this->callHook('beforeValidate');

            $data = $this->form->getState();

            $this->callHook('afterValidate');

            $data = $this->mutateFormDataBeforeCreate($data);

            /** @internal Read the DocBlock above the following method. */
            $this->createRecordAndCallHooks($data);

            DB::commit();

        } catch (\Throwable $exception) {
            DB::rollBack();
            dd($exception);
            fns()->displayException($exception);
            fns()->sendDanger('خطأ', 'فشلت العمليلة الرجاء التواصل مع الدعم الفني');
            $this->halt();
        }

        /** @internal Read the DocBlock above the following method. */
        $this->sendCreatedNotificationAndRedirect(shouldCreateAnotherInsteadOfRedirecting: $another);
    }

}
