<?php

namespace App\Filament\Tenant\Resources\PurchaseInvoiceResource\Pages;

use App\Filament\Tenant\Resources\PurchaseInvoiceResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;

class EditPurchaseInvoice extends EditRecord
{
    protected static string $resource = PurchaseInvoiceResource::class;

    protected function getActions(): array
    {
        return [
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['discount_option_overall'] = $this->record->discount_option == "overall";
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }

    protected function beforeSave(): void
    {
        //check for duplicates
        foreach ($this->data['items'] ?? [] as $item)
        {
            $exists = collect($this->data['items'] ?? [])
                ->where('id', '!=', $item['id'])
                ->where('product_id', $item['product_id'])
                ->where('unit_id', $item['unit_id'])
                ->first();

            if($exists){
                fns()->sendWarning("Duplicate product/unit.");
                $this->halt();
            }
        }
    }

    protected function getFormActions(): array
    {
        if ($this->record->locked_at !== null) {
            fns()->sendWarning(__('fields.invoice_locked_statement'));
            return [];
        }

        return parent::getFormActions();
    }
}
