<?php

namespace App\Filament\Tenant\Resources\PurchaseInvoiceResource\Pages;

use App\Filament\MyActions\Pages\AddToFavourites;
use App\Filament\Tenant\Pages\Subscription;
use App\Filament\Tenant\Resources\OrderResource;
use App\Filament\Tenant\Resources\PurchaseInvoiceResource;
use App\Filament\Tenant\Resources\PurchaseInvoiceStatusResource;
use App\Models\PriceOffer;
use App\Models\SupplyOrder;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Actions\CreateAction;
use Filament\Forms\Components\Select;
use Filament\Resources\Pages\ListRecords;
use Filament\Support\Colors\Color;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\HtmlString;

class ListPurchaseInvoices extends ListRecords
{
    protected static string $resource = PurchaseInvoiceResource::class;

    public function getSubheading(): string|Htmlable|null
    {
        if(purchases_invoices_maxed_out()){
            $msg = __('fields.sales_invoices_maxed_out_alert');
            $url = Subscription::getUrl();
            if(str($msg)->contains('بترقية')){
                $link_text = "بترقية خطتك";
                $msg = str($msg)->replace('بترقية خطتك', "<a style='color: #0000cc; text-decoration: underline' href='$url'> $link_text </a>");
            }else{
                $msg = str($msg)->replace('upgrade your plan', "<a style='color: #0000cc; text-decoration: underline' href='$url'> upgrade your plan </a>");
            }
            return new HtmlString("<span class='text-sm font-bold' style='color: #e15858;'>$msg</span>");
        }
        return parent::getSubheading(); // TODO: Change the autogenerated stub
    }
    protected function getActions(): array
    {
        return [
            AddToFavourites::make('fav')
                ->settingKey('fav.orders'),

            ActionGroup::make([

                CreateAction::make(),

                Action::make('make_purchases_invoice_from_supply_order')
                    ->label(__('fields.make_purchases_invoice_from_supply_order'))
                    ->requiresConfirmation()
                    ->color(Color::Sky)
                    ->form([
                        Select::make('supply_order_id')
                            ->required()
                            ->label(__('fields.supply_order'))
                            ->searchable()
                            ->options(function () {
                                $data = [];
                                foreach (SupplyOrder::all() as $item) {
                                    $data[$item->id] = $item->no . " - " . $item->description;
                                }
                                return $data;
                            })
                    ])->action(function ($data) {
                        $this->redirect(PurchaseInvoiceResource::getUrl('create', ['supply_order_id' => $data['supply_order_id']]));
                    }),
            ])->button(),
        ];
    }
}
