<?php

namespace App\Filament\Tenant\Resources\ExpenseCategoryResource\Pages;

use App\Filament\MyActions\Pages\AddToFavourites;
use App\Filament\Tenant\Pages\Settings;
use App\Filament\Tenant\Resources\ExpenseCategoryResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;

class ListExpenseCategories extends ListRecords
{
    protected static string $resource = ExpenseCategoryResource::class;

    public function getBreadcrumbs(): array
    {
        return array_merge([
            Settings::getUrl() => __('fields.settings')
        ], parent::getBreadcrumbs()); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            AddToFavourites::make('fav')
                ->settingKey('fav.expenses_categories'),
            Actions\CreateAction::make(),
        ];
    }
}
