<?php

namespace App\Filament\Tenant\Resources\SalesInvoiceResource\Pages;

use App\Filament\Tenant\Resources\SalesInvoiceResource;
use App\Models\AdditionalCost;
use App\Models\InvoiceItem;
use App\Models\PriceOffer;
use App\Models\PriceOfferDetails;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Models\TaxProfile;
use App\Services\CacheService;
use App\Services\PricingService;
use App\Services\StockService;
use Filament\Resources\Pages\CreateRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class CreateSalesInvoice extends CreateRecord
{
    protected static string $resource = SalesInvoiceResource::class;

    protected $price_offer_id, $items;

    public function mount(): void
    {
        parent::mount(); // TODO: Change the autogenerated stub

        $this->price_offer_id = request('price_offer_id', null);

        $priceOffer = PriceOffer::with('details.item.prices', 'details.offerDetailsExtras', 'AdditionalCosts', 'services')->find($this->price_offer_id);

        if ($priceOffer) {

            $items = [];
            $services = [];
            $additional_costs = [];

            foreach ($priceOffer->details as $detail) {
                $items[Str::uuid()->toString()] = [
                    'tenant_id' => $detail->tenant_id,
                    'product_id' => $detail->item instanceof Product ? $detail->item->id : $detail->item->product->id,
                    'product_variant_id' => $detail->item instanceof ProductVariant ? $detail->item->id : null,
                    'item_id' => $detail->item_id,
                    'item_type' => $detail->item_type,
                    'type' => $detail->item_type,
                    'display_name' => $detail->item->name,
                    'name' => $detail->item->name,
                    'max_qty' => StockService::instance()->getAvailableStock($detail->item),
                    'qty' => $detail->qty,
                    'discount' => number_format($detail->discount, currency_decimals(), '.', ''),
                    'price' => number_format($detail->unit_price, currency_decimals(), '.', ''),
                    'tax' => PricingService::instance()->getTaxAmount($detail->item instanceof Product ? $detail->item : $detail->item->product, $detail->unit_price, $detail->qty),
                    'product_extras_ids' => $detail->offerDetailsExtras->pluck('product_extra_id')->toArray(),
                    'extras_total' => PricingService::instance()->getRetailPrices(ProductExtra::with('lastPrice')->findMany($detail->offerDetailsExtras->pluck('product_extra_id')->toArray())),
                    'extras' => implode(', ', ProductExtra::findMany($detail->offerDetailsExtras->pluck('product_extra_id')->toArray())->pluck('name')->toArray()),
                    'tax_profile_id' => $detail->tax_profile_id,
                    'tax_profile_data' => TaxProfile::find($detail->tax_profile_id)?->toArray(),
                    'sub_total' => format_amount(($detail->qty * $detail->unit_price)),
                ];
            }

            foreach ($priceOffer->services as $service) {
                $price = number_format($service->price, currency_decimals(), '.', '');

                $price_after_tax = $price;

                if ($taxProfile = TaxProfile::with('taxes')->find($service->tax_profile_id)) {
                    $tax = $service->price * ($taxProfile->total_percentages / 100);
                    $price_after_tax = number_format($service->price + $tax, currency_decimals(), '.', '');
                }

                $services[Str::uuid()->toString()] = [
                    'tenant_id' => $service->tenant_id,
                    'service_type_id' => $service->service_type_id,
                    'price' => $price,
                    'price_after_tax' => $price_after_tax,
                    'description' => $service->description,
                    'tax_profile_id' => $service->tax_profile_id,
                    'tax_profile_data' => TaxProfile::find($service->tax_profile_id)?->toArray(),
                ];
            }

            foreach ($priceOffer->additionalCosts as $additionalCost) {
                $additional_costs[Str::uuid()->toString()] = [
                    'tenant_id' => $additionalCost->tenant_id,
                    'additional_cost_type_id' => $additionalCost->additional_cost_type_id,
                    'cost' => number_format($additionalCost->cost, currency_decimals(), '.', ''),
                    'statement' => $additionalCost->statement,
                ];
            }

            $this->data['discount_option_overall'] = $priceOffer->discount_option == "overall";
            $this->data['discount_option'] = $priceOffer->discount_option;
            $this->data['discount_method'] = $priceOffer->discount_method;
            $this->data['discount_amount'] = $priceOffer->discount_amount;
            $this->data['discount_percent'] = $priceOffer->discount_percent;

            $this->form->fill([
                'date' => now(),
                'status' => 'sale_order',
                'type' => 'sales',
                'for' => 'customer',
                'no' => generate_invoice_no(),
                'price_offer_id' => $priceOffer->id,
                'customer_id' => $priceOffer->customer_id,
                'discount_option_overall' => $priceOffer->discount_option == "overall",
                'discount_option' => $priceOffer->discount_option,
                'discount_method' => $priceOffer->discount_method,
                'discount_amount' => $priceOffer->discount_amount,
                'discount_percent' => $priceOffer->discount_percent,
                'items' => $items,
                'services' => $services,
                'additional_costs' => $additional_costs,
            ]);

            $this->data['items'] = $items;

            self::updateInvoicePropertiesFromLivewire($this);
        }
    }

    protected function afterCreate(): void
    {
        $this->saveItems($this->record->id, $this->data);
    }

    protected function saveItems($invoice_id, $data)
    {
        foreach ($data['items'] as $index => $detail) {
            $taxProfile = null;

            $item = app()->make($detail['item_type'])->where('id', $detail['item_id'])->first();

            if ($item instanceof Product) {
                $taxProfile = $item->taxProfile;
            }

            if ($item instanceof ProductVariant) {
                $taxProfile = $item->product->taxProfile;
            }

            if ($taxProfile)
                $taxProfile->load('taxes');

            $invoiceItem = InvoiceItem::create([
                'user_id' => auth()->id(),
                'tenant_id' => $detail['tenant_id'],
                'invoice_id' => $invoice_id,
                'name' => $detail['name'],
                'product_variant_id' => $detail['product_variant_id'],
                'product_id' => $detail['product_id'],
                'price' => $detail['price'],
                'qty' => $detail['qty'],
                'discount' => $detail['discount'],
                'tax' => $detail['tax'],
                'tax_profile_id' => $taxProfile?->id,
                'tax_profile_data' => $taxProfile?->toArray(),
            ]);

            foreach ($detail['product_extras_ids'] ?? [] as $product_extra_id) {

                $productExtra = ProductExtra::with(['lastPrice', 'extra'])->findOrFail($product_extra_id);

                $invoiceItem->extras()->create([
                    'tenant_id' => $detail['tenant_id'],
                    'invoice_item_id' => $invoiceItem->id,
                    'product_extra_id' => $product_extra_id,
                    'unit_price' => PricingService::instance()->getRetailPrice($productExtra),
                    'display_name' => $productExtra->name,
                    'qty' => 1,
                ]);
            }
        }
    }

    public function updateInvoicePropertiesFromLivewire($createSalesInvoice): array
    {
        $startTime = microtime(true);

        self::updateItemsDiscount($createSalesInvoice);

        $items = $createSalesInvoice->data['items'] ?? [];
        $services = $createSalesInvoice->data['services'] ?? [];
        $additionalCosts = $createSalesInvoice->data['additional_costs'] ?? [];
        $discountOption = $createSalesInvoice->data['discount_option'] ?? [];
        $discountMethod = $createSalesInvoice->data['discount_method'] ?? null;
        $discountAmount = $createSalesInvoice->data['discount_amount'] ?? null;
        $discountPercent = $createSalesInvoice->data['discount_percent'] ?? [];

        $totals = [
            'total_purchases' => 0,
            'total_additional_costs' => 0,
            'total_services' => 0,
            'total_discount' => 0,
            'total_taxes' => 0,
            'execution_time' => 0,
        ];

        $taxProfiles = CacheService::instance()->remember('taxProfiles', 5 * 60, function () {
            return TaxProfile::all();
        });

        foreach ($items as $item) {

            $price = $item['price'] ?? 0;
            $qty = $item['qty'] ?? 0;
            $extras_total = $item['extras_total'] ?? 0;
            $discount = $item['discount'] ?? 0;
            $tax = 0;

            if (is_number($qty) and is_number($price))
                $totals['total_purchases'] += $qty * $price;

            $totals['total_purchases'] += $extras_total;

            if ($discountOption == "per-item" and is_number($discount))
                $totals['total_discount'] += $discount;

            $taxProfileId = $item['tax_profile_id'] ?? null;

            if ($taxProfileId and is_number($price) and is_number($qty)) {
                $taxProfile = $taxProfiles->where('id', $taxProfileId)->first();

                if (!$taxProfile)
                    $taxProfile = TaxProfile::find($taxProfileId);

                if ($taxProfile) {
                    $sub_total = ($price * $qty) + $extras_total;

                    if (is_number($discount))
                        $sub_total -= $discount;

                    $tax = $sub_total * ($taxProfile->total_percentages / 100);
                    $totals['total_taxes'] += $sub_total * ($taxProfile->total_percentages / 100);
                }
            }

        }

        foreach ($services as $service) {
            $price = $service['price'] ?? 0;
            $totals['total_services'] += $price;
            $total_percentages = collect($service['tax_profile_data']['taxes'] ?? [])->sum('percent');
            if ($total_percentages > 0) {
                $totals['total_taxes'] += $price * ($total_percentages / 100);
            }
        }

        if ($discountOption == "overall" and $discountMethod == "amount" and is_number($discountAmount))
            $totals['total_discount'] = $discountAmount;

        if ($discountOption == "overall" and $discountMethod == "percent" and is_number($discountPercent)) {
//            20/100 = 0.2
            $discountInAmount = $totals['total_purchases'] * ($discountPercent / 100);

            $totals['total_discount'] = number_format($discountInAmount, currency_decimals(), '.', '');

        }

        foreach ($additionalCosts as $item) {
            if (is_number($cost = $item['cost'])) {
                $totals['total_additional_costs'] += $cost;
            }
        }

        $createSalesInvoice->data['total_invoice_pre_discount_pre_tax'] = format_amount($totals['total_purchases'] + $totals['total_services'] + $totals['total_additional_costs']);
        $createSalesInvoice->data['total_discount'] = format_amount($totals['total_discount']);
        $createSalesInvoice->data['total_taxes'] = format_amount($totals['total_taxes']);
        $createSalesInvoice->data['total_invoice_post_discount'] = format_amount($totals['total_purchases'] + $totals['total_services'] + $totals['total_additional_costs'] - $totals['total_discount']);
        $createSalesInvoice->data['total_invoice_with_taxes'] = format_amount($totals['total_purchases'] + $totals['total_services'] + $totals['total_additional_costs'] - $totals['total_discount'] + $totals['total_taxes']);


        $endTime = microtime(true);

        $totals['execution_time'] = $endTime - $startTime;

        return $totals;
    }

    public function updateItemsDiscount($createSalesInvoice)
    {

        $taxProfiles = CacheService::instance()->remember('taxProfiles', 5 * 60, function () {
            return TaxProfile::all();
        });

        $discountOption = $createSalesInvoice->data['discount_option'] ?? null;
        $discountMethod = $createSalesInvoice->data['discount_method'] ?? null;
        $discountAmount = $createSalesInvoice->data['discount_amount'] ?? $createSalesInvoice->data['discount_percent'] ?? null;

        $newItems = [];
        foreach ($createSalesInvoice->data['items'] ?? [] as $item) {
            $extras_total = $item['extras_total'] ?? 0;

            $price = $item['price'] ?? null;
            $qty = $item['qty'] ?? null;
            $tax = 0;

            if ($discountOption == "overall") {
                if ($discountMethod == "percent") {
                    if (is_number($price) and is_number($qty)) {
                        $amountFromPercent = ($price * $qty) * ($discountAmount / 100);
                        $item['discount'] = number_format($amountFromPercent, currency_decimals(), '.', '');
                    } else {
                        $item['discount'] = -1;
                    }

                } else {
                    $item['discount'] = is_number($discountAmount) ? number_format($discountAmount, currency_decimals(), '.', '') : null;
                }
            }

            //set sub_total
            if (is_number($price) and is_number($qty)) {
                $discount = $item['discount'] ?? null;

                if (!$discount or $discount < 0)
                    $discount = 0;

                $subTotal = ($price * $qty) + $extras_total;
                $subTotal -= $discount;

                if (is_number($item['tax_profile_id'] ?? null)) {
                    $taxProfileId = $item['tax_profile_id'];

                    $taxProfile = $taxProfiles->where('id', $taxProfileId)->first();

                    if (!$taxProfile)
                        $taxProfile = TaxProfile::find($taxProfileId);

                    if ($taxProfile) {
                        $tax = $subTotal * ($taxProfile->total_percentages / 100);
                        $subTotal += $tax;
                    }
                }

                $item['tax'] = $tax;

                $item['sub_total'] = format_amount($subTotal);


            }
            $newItems[] = $item;
        }

        $createSalesInvoice->data['items'] = $newItems;
    }
}
