<?php

namespace App\Filament\Tenant\Resources\SalesInvoiceResource\Pages;

use App\Filament\Tenant\Resources\SalesInvoiceResource;
use App\Models\InvoiceItem;
use App\Models\PriceOfferDetails;
use App\Models\Product;
use App\Models\ProductExtra;
use App\Models\ProductVariant;
use App\Models\TaxProfile;
use App\Services\PricingService;
use Filament\Infolists\Infolist;
use Filament\Pages\Actions;
use Filament\Resources\Pages\EditRecord;
use Filament\Support\Exceptions\Halt;
use Filament\Support\Facades\FilamentView;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Validation\ValidationException;
use function Filament\Support\is_app_url;

class EditSalesInvoice extends EditRecord
{
    protected static string $resource = SalesInvoiceResource::class;

    protected function getActions(): array
    {
        return [
        ];
    }

    protected function getFormActions(): array
    {
        if ($this->record->locked_at !== null) {
            fns()->sendWarning(__('fields.invoice_locked_statement'));
            return [];
        }

        return parent::getFormActions();
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data['discount_option_overall'] = $this->record->discount_option == "overall";

        $items = [];
        foreach ($this->record->items as $invoiceItem) {
            $items[Str::uuid()->toString()] = [
                'id' => $invoiceItem->id,
                "tenant_id" => $invoiceItem->tenant_id,
                "user_id" => $invoiceItem->user_id,
                "max_qty" => 1000,
                "item_id" => $invoiceItem->item_id,
                "item_type" => $invoiceItem->item_type,
                "unit_price" => number_format($invoiceItem->price, currency_decimals(), '.', ''),
                "discount" => number_format($invoiceItem->discount, currency_decimals(), '.', ''),
                "product_id" => $invoiceItem->product_id,
                'product_variant_id' => $invoiceItem->product_variant_id,
                'product_extras_ids' => $invoiceItem->extras->pluck('product_extra_id')->toArray(),
                'extras_total' => PricingService::instance()->getRetailPrices(ProductExtra::with('lastPrice')->findMany($invoiceItem->extras->pluck('product_extra_id')->toArray())),
                "extras" => implode(', ', $invoiceItem->extras->pluck('display_name')->toArray()),
                "qty" => $invoiceItem->qty,
                'name' => $invoiceItem->name,
                "price" => number_format($invoiceItem->price, currency_decimals(), '.', ''),
                "tax" => number_format($invoiceItem->tax, currency_decimals(), '.', ''),
                'tax_profile_id' => $invoiceItem->tax_profile_id,
                'tax_profile_data' => TaxProfile::find($invoiceItem->tax_profile_id)?->toArray(),
                "sub_total" => number_format($invoiceItem->qty * $invoiceItem->price, currency_decimals(), '.', ''),
            ];
        }

        $data['items'] = $items;
        return parent::mutateFormDataBeforeFill($data); // TODO: Change the autogenerated stub
    }



    protected function afterSave(): void
    {
        $this->record->load(['items']);

        //save items
        foreach ($this->record->items as $item){
            $item->extras()->delete();
            $item->delete();
        }
        $this->saveItems($this->data);
    }

    protected function saveItems($data)
    {
        foreach ($data['items'] as $index => $invoiceItem) {

            $taxProfile = TaxProfile::find($invoiceItem['tax_profile_id'] ?? null);

            if ($taxProfile)
                $taxProfile->load('taxes');

            $ii = InvoiceItem::create([
                'user_id' => auth()->id(),
                'tenant_id' => $invoiceItem['tenant_id'],
                'invoice_id' => $this->record->id,
                'name' => $invoiceItem['name'],
                'product_variant_id' => $invoiceItem['product_variant_id'],
                'product_id' => $invoiceItem['product_id'],
                'price' => $invoiceItem['price'],
                'qty' => $invoiceItem['qty'],
                'discount' => $invoiceItem['discount'],
                'tax' => $invoiceItem['tax'],
                'tax_profile_id' => $taxProfile?->id,
                'tax_profile_data' => $taxProfile?->toArray(),
            ]);

            foreach ($invoiceItem['product_extras_ids'] ?? [] as $product_extra_id) {

                $productExtra = ProductExtra::with(['lastPrice', 'extra'])->findOrFail($product_extra_id);

                $ii->extras()->create([
                    'tenant_id' => $invoiceItem['tenant_id'],
                    'invoice_item_id' => $ii->id,
                    'product_extra_id' => $product_extra_id,
                    'unit_price' => PricingService::instance()->getRetailPrice($productExtra),
                    'display_name' => $productExtra->name,
                    'qty' => 1,
                ]);
            }
        }
    }
}
