<?php

namespace App\Filament\Tenant\Resources\SalesInvoiceResource\Pages;

use App\Filament\MyActions\Pages\AddToFavourites;
use App\Filament\Tenant\Pages\Subscription;
use App\Filament\Tenant\Resources\SalesInvoiceResource;
use App\Models\PriceOffer;
use Filament\Actions\Action;
use Filament\Actions\ActionGroup;
use Filament\Actions\CreateAction;
use Filament\Forms\Components\Select;
use Filament\Resources\Pages\ListRecords;
use Filament\Support\Colors\Color;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Support\HtmlString;

class ListSalesInvoices extends ListRecords
{
    protected static string $resource = SalesInvoiceResource::class;

    public function getSubheading(): string|Htmlable|null
    {
        if(!sales_invoices_maxed_out()){
            $msg = __('fields.sales_invoices_maxed_out_alert');
            $url = Subscription::getUrl();
            if(str($msg)->contains('بترقية')){
                $link_text = "بترقية خطتك";
                $msg = str($msg)->replace('بترقية خطتك', "<a style='color: #0000cc; text-decoration: underline' href='$url'> $link_text </a>");
            }else{
                $msg = str($msg)->replace('upgrade your plan', "<a style='color: #0000cc; text-decoration: underline' href='$url'> upgrade your plan </a>");
            }
            return new HtmlString("<span class='text-sm font-bold' style='color: #e15858;'>$msg</span>");
        }
        return parent::getSubheading(); // TODO: Change the autogenerated stub
    }

    protected function getActions(): array
    {
        return [
            AddToFavourites::make('fav')
                ->settingKey('fav.sales_invoices'),

            ActionGroup::make([

                CreateAction::make()
                    ->disabled(fn() => sales_invoices_maxed_out()),

                Action::make('make_sales_invoice_from_price_offer')
                    ->disabled(fn() => sales_invoices_maxed_out())
                    ->label(__('fields.make_sales_invoice_from_price_offer'))
                    ->requiresConfirmation()
                    ->color(Color::Sky)
                    ->form([
                        Select::make('price_offer_id')
                            ->required()
                            ->label(__('fields.price_offers'))
                            ->searchable()
                            ->options(function () {
                                $data = [];
                                foreach (PriceOffer::all() as $priceOffer) {
                                    $data[$priceOffer->id] = $priceOffer->no . " - " . $priceOffer->description;
                                }
                                return $data;
                            })
                    ])->action(function ($data) {
                        $this->redirect(SalesInvoiceResource::getUrl('create', ['price_offer_id' => $data['price_offer_id']]));
                    }),

            ])->button(),
        ];
    }
}
